
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.fightsfrights.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.fightsfrights.item.WitheredProboscisItem;
import net.mcreator.fightsfrights.item.UltimateMethodUpdatedItem;
import net.mcreator.fightsfrights.item.TerrifyingProboscisItem;
import net.mcreator.fightsfrights.item.TerrantulaLegItem;
import net.mcreator.fightsfrights.item.SyringeItem;
import net.mcreator.fightsfrights.item.ShackleItem;
import net.mcreator.fightsfrights.item.RottenHandleItem;
import net.mcreator.fightsfrights.item.RavagerHornItem;
import net.mcreator.fightsfrights.item.PutridScythe2Item;
import net.mcreator.fightsfrights.item.PungentSoupItem;
import net.mcreator.fightsfrights.item.PoisonousProboscisItem;
import net.mcreator.fightsfrights.item.PoisonOrbItemItem;
import net.mcreator.fightsfrights.item.PathogenItem;
import net.mcreator.fightsfrights.item.OminousTuskItem;
import net.mcreator.fightsfrights.item.OminousScepterItem;
import net.mcreator.fightsfrights.item.OminousPlateItem;
import net.mcreator.fightsfrights.item.OminousEssenceItem;
import net.mcreator.fightsfrights.item.OminousArmorItem;
import net.mcreator.fightsfrights.item.NightmareItem;
import net.mcreator.fightsfrights.item.MonstruousPlateItem;
import net.mcreator.fightsfrights.item.MonstrousArmorItem;
import net.mcreator.fightsfrights.item.MonsterSaladItem;
import net.mcreator.fightsfrights.item.MonsterPopItem;
import net.mcreator.fightsfrights.item.MimicBeetleItem;
import net.mcreator.fightsfrights.item.MimentisClawSingleUseItem;
import net.mcreator.fightsfrights.item.MimentisClawItem;
import net.mcreator.fightsfrights.item.InfectiousProboscisItem;
import net.mcreator.fightsfrights.item.HexItem;
import net.mcreator.fightsfrights.item.GoopItem;
import net.mcreator.fightsfrights.item.GoldenTongueItem;
import net.mcreator.fightsfrights.item.GillsItem;
import net.mcreator.fightsfrights.item.ForewingsItem;
import net.mcreator.fightsfrights.item.EmptyHexItem;
import net.mcreator.fightsfrights.item.ElderSpineItem;
import net.mcreator.fightsfrights.item.DeadsteelScimitarItem;
import net.mcreator.fightsfrights.item.ChitinItem;
import net.mcreator.fightsfrights.item.ChipItem;
import net.mcreator.fightsfrights.item.CheeseStickItem;
import net.mcreator.fightsfrights.item.ChargedScrapItem;
import net.mcreator.fightsfrights.item.ChargedFleshItem;
import net.mcreator.fightsfrights.item.ChargedChiliItem;
import net.mcreator.fightsfrights.item.BugDustItem;
import net.mcreator.fightsfrights.item.BluntJavelinItem;
import net.mcreator.fightsfrights.item.BlindingProboscisItem;
import net.mcreator.fightsfrights.item.BanshaasLungsItem;
import net.mcreator.fightsfrights.item.AntidoteItem;
import net.mcreator.fightsfrights.item.AllbombItem;
import net.mcreator.fightsfrights.FightsfrightsMod;

public class FightsfrightsModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(FightsfrightsMod.MODID);
	public static final DeferredItem<Item> ALLMAN_SPAWN_EGG = REGISTRY.register("allman_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.ALLMAN, -12702429, -8875630, new Item.Properties()));
	public static final DeferredItem<Item> SCOWL_SPAWN_EGG = REGISTRY.register("scowl_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.SCOWL, -9399763, -10079488, new Item.Properties()));
	public static final DeferredItem<Item> SHACKLE = REGISTRY.register("shackle", ShackleItem::new);
	public static final DeferredItem<Item> ROTTEN_HANDLE = REGISTRY.register("rotten_handle", RottenHandleItem::new);
	public static final DeferredItem<Item> GOLDEN_TONGUE = REGISTRY.register("golden_tongue", GoldenTongueItem::new);
	public static final DeferredItem<Item> GOOP = REGISTRY.register("goop", GoopItem::new);
	public static final DeferredItem<Item> MONSTER_POP = REGISTRY.register("monster_pop", MonsterPopItem::new);
	public static final DeferredItem<Item> SEER_SPAWN_EGG = REGISTRY.register("seer_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.SEER, -14264977, -13966086, new Item.Properties()));
	public static final DeferredItem<Item> PATUTI_SPAWN_EGG = REGISTRY.register("patuti_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.PATUTI, -8992319, -12967067, new Item.Properties()));
	public static final DeferredItem<Item> GILLS = REGISTRY.register("gills", GillsItem::new);
	public static final DeferredItem<Item> PIONEER_SPAWN_EGG = REGISTRY.register("pioneer_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.PIONEER, -15658479, -14031283, new Item.Properties()));
	public static final DeferredItem<Item> CHIP = REGISTRY.register("chip", ChipItem::new);
	public static final DeferredItem<Item> TERRANTULA_SPAWN_EGG = REGISTRY.register("terrantula_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.TERRANTULA, -5477120, -8370416, new Item.Properties()));
	public static final DeferredItem<Item> TERRANTULA_LEG = REGISTRY.register("terrantula_leg", TerrantulaLegItem::new);
	public static final DeferredItem<Item> BANSHAA_SPAWN_EGG = REGISTRY.register("banshaa_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.BANSHAA, -2630683, -6772262, new Item.Properties()));
	public static final DeferredItem<Item> BANSHAAS_LUNGS = REGISTRY.register("banshaas_lungs", BanshaasLungsItem::new);
	public static final DeferredItem<Item> MONSTER_SALAD = REGISTRY.register("monster_salad", MonsterSaladItem::new);
	public static final DeferredItem<Item> ROTTEN_BLOCK = block(FightsfrightsModBlocks.ROTTEN_BLOCK);
	public static final DeferredItem<Item> TOTEM_BLOCK = block(FightsfrightsModBlocks.TOTEM_BLOCK);
	public static final DeferredItem<Item> EMPTY_HEX_BLOCK = block(FightsfrightsModBlocks.EMPTY_HEX_BLOCK);
	public static final DeferredItem<Item> HEX = REGISTRY.register("hex", HexItem::new);
	public static final DeferredItem<Item> EMPTY_HEX = REGISTRY.register("empty_hex", EmptyHexItem::new);
	public static final DeferredItem<Item> HEXBLOCK = block(FightsfrightsModBlocks.HEXBLOCK);
	public static final DeferredItem<Item> RAVAGER_HORN = REGISTRY.register("ravager_horn", RavagerHornItem::new);
	public static final DeferredItem<Item> ELDER_SPINE = REGISTRY.register("elder_spine", ElderSpineItem::new);
	public static final DeferredItem<Item> MONSTRUOUS_PLATE = REGISTRY.register("monstruous_plate", MonstruousPlateItem::new);
	public static final DeferredItem<Item> MONSTROUS_ARMOR_HELMET = REGISTRY.register("monstrous_armor_helmet", MonstrousArmorItem.Helmet::new);
	public static final DeferredItem<Item> MONSTROUS_ARMOR_CHESTPLATE = REGISTRY.register("monstrous_armor_chestplate", MonstrousArmorItem.Chestplate::new);
	public static final DeferredItem<Item> MONSTROUS_ARMOR_LEGGINGS = REGISTRY.register("monstrous_armor_leggings", MonstrousArmorItem.Leggings::new);
	public static final DeferredItem<Item> MONSTROUS_ARMOR_BOOTS = REGISTRY.register("monstrous_armor_boots", MonstrousArmorItem.Boots::new);
	public static final DeferredItem<Item> BLIGHT_STEM = block(FightsfrightsModBlocks.BLIGHT_STEM);
	public static final DeferredItem<Item> BLLIGHT_CAP_BLOCK = block(FightsfrightsModBlocks.BLLIGHT_CAP_BLOCK);
	public static final DeferredItem<Item> BLIGHTCAP = block(FightsfrightsModBlocks.BLIGHTCAP);
	public static final DeferredItem<Item> DARK_TRAMA = block(FightsfrightsModBlocks.DARK_TRAMA);
	public static final DeferredItem<Item> BLIGHT_PLANKS = block(FightsfrightsModBlocks.BLIGHT_PLANKS);
	public static final DeferredItem<Item> BLIGHT_HYPHAE = block(FightsfrightsModBlocks.BLIGHT_HYPHAE);
	public static final DeferredItem<Item> BLIGHT_STAIRS = block(FightsfrightsModBlocks.BLIGHT_STAIRS);
	public static final DeferredItem<Item> BLIGHT_SLAB = block(FightsfrightsModBlocks.BLIGHT_SLAB);
	public static final DeferredItem<Item> BLIGHT_FENCE = block(FightsfrightsModBlocks.BLIGHT_FENCE);
	public static final DeferredItem<Item> BLIGHT_FENCEGATE = block(FightsfrightsModBlocks.BLIGHT_FENCEGATE);
	public static final DeferredItem<Item> BLIGHT_BUTTON = block(FightsfrightsModBlocks.BLIGHT_BUTTON);
	public static final DeferredItem<Item> BLIGHT_TRAPDOOR = block(FightsfrightsModBlocks.BLIGHT_TRAPDOOR);
	public static final DeferredItem<Item> BLIGHTDOOR = doubleBlock(FightsfrightsModBlocks.BLIGHTDOOR);
	public static final DeferredItem<Item> CRUSHER = block(FightsfrightsModBlocks.CRUSHER);
	public static final DeferredItem<Item> REANIMATED_SPAWN_EGG = REGISTRY.register("reanimated_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.REANIMATED, -4035764, -1579109, new Item.Properties()));
	public static final DeferredItem<Item> CHARGED_SCRAP = REGISTRY.register("charged_scrap", ChargedScrapItem::new);
	public static final DeferredItem<Item> CHARGED_FLESH = REGISTRY.register("charged_flesh", ChargedFleshItem::new);
	public static final DeferredItem<Item> GHASTLY_GENERAL_SPAWN_EGG = REGISTRY.register("ghastly_general_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.GHASTLY_GENERAL, -13884353, -65425, new Item.Properties()));
	public static final DeferredItem<Item> POISON_ORB_ITEM = REGISTRY.register("poison_orb_item", PoisonOrbItemItem::new);
	public static final DeferredItem<Item> DEADSTEEL_SCIMITAR = REGISTRY.register("deadsteel_scimitar", DeadsteelScimitarItem::new);
	public static final DeferredItem<Item> PUTRID_SCYTHE_2 = REGISTRY.register("putrid_scythe_2", PutridScythe2Item::new);
	public static final DeferredItem<Item> SHACKLED_SPAWN_EGG = REGISTRY.register("shackled_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.SHACKLED, -2958626, -8875630, new Item.Properties()));
	public static final DeferredItem<Item> ALLBOMB = REGISTRY.register("allbomb", AllbombItem::new);
	public static final DeferredItem<Item> PIGLIN_PROSECUTOR_SPAWN_EGG = REGISTRY.register("piglin_prosecutor_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.PIGLIN_PROSECUTOR, -1531788, -65425, new Item.Properties()));
	public static final DeferredItem<Item> BLUNT_JAVELIN = REGISTRY.register("blunt_javelin", BluntJavelinItem::new);
	public static final DeferredItem<Item> PUNGENT_SOUP = REGISTRY.register("pungent_soup", PungentSoupItem::new);
	public static final DeferredItem<Item> OMINOUS_TUSK = REGISTRY.register("ominous_tusk", OminousTuskItem::new);
	public static final DeferredItem<Item> IMPERIAL_ILLAGER_P_1_SPAWN_EGG = REGISTRY.register("imperial_illager_p_1_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.IMPERIAL_ILLAGER_P_1, -8220261, -65425, new Item.Properties()));
	public static final DeferredItem<Item> IMPERIAL_ILLAGER_P_2_SPAWN_EGG = REGISTRY.register("imperial_illager_p_2_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.IMPERIAL_ILLAGER_P_2, -13808286, -65425, new Item.Properties()));
	public static final DeferredItem<Item> OMINOUS_SCEPTER = REGISTRY.register("ominous_scepter", OminousScepterItem::new);
	public static final DeferredItem<Item> EFFIGY_SPAWN_EGG = REGISTRY.register("effigy_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.EFFIGY, -665046, -9448139, new Item.Properties()));
	public static final DeferredItem<Item> VSD = block(FightsfrightsModBlocks.VSD);
	public static final DeferredItem<Item> CHARGED_CHILI = REGISTRY.register("charged_chili", ChargedChiliItem::new);
	public static final DeferredItem<Item> CHEESE_STICK = REGISTRY.register("cheese_stick", CheeseStickItem::new);
	public static final DeferredItem<Item> WICKE_WARMONGER_SPAWN_EGG = REGISTRY.register("wicke_warmonger_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.WICKE_WARMONGER, -16724737, -65425, new Item.Properties()));
	public static final DeferredItem<Item> FISSURED_NETHERRACK = block(FightsfrightsModBlocks.FISSURED_NETHERRACK);
	public static final DeferredItem<Item> MALICIOUS_MONARCH_P_1_SPAWN_EGG = REGISTRY.register("malicious_monarch_p_1_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.MALICIOUS_MONARCH_P_1, -458497, -65425, new Item.Properties()));
	public static final DeferredItem<Item> MALICIOUS_MONARCH_P_2_SPAWN_EGG = REGISTRY.register("malicious_monarch_p_2_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.MALICIOUS_MONARCH_P_2, -55058, -65425, new Item.Properties()));
	public static final DeferredItem<Item> CALLOUS_COMMANDER_1_SPAWN_EGG = REGISTRY.register("callous_commander_1_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.CALLOUS_COMMANDER_1, -13828343, -65425, new Item.Properties()));
	public static final DeferredItem<Item> ULTIMATE_METHOD_UPDATED = REGISTRY.register("ultimate_method_updated", UltimateMethodUpdatedItem::new);
	public static final DeferredItem<Item> MIMIC_BEETLE = REGISTRY.register("mimic_beetle", MimicBeetleItem::new);
	public static final DeferredItem<Item> GRIMMSQUITO_SPAWN_EGG = REGISTRY.register("grimmsquito_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.GRIMMSQUITO, -12116201, -5043164, new Item.Properties()));
	public static final DeferredItem<Item> FOREWINGS = REGISTRY.register("forewings", ForewingsItem::new);
	public static final DeferredItem<Item> BUG_DUST = REGISTRY.register("bug_dust", BugDustItem::new);
	public static final DeferredItem<Item> SHADOW_SPAWN_EGG = REGISTRY.register("shadow_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.SHADOW, -16777216, -13421773, new Item.Properties()));
	public static final DeferredItem<Item> SHADOWCOMPANION_SPAWN_EGG = REGISTRY.register("shadowcompanion_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.SHADOWCOMPANION, -16777216, -13421773, new Item.Properties()));
	public static final DeferredItem<Item> SHADOWCOMPANIONCOMPANION_SPAWN_EGG = REGISTRY.register("shadowcompanioncompanion_spawn_egg",
			() -> new DeferredSpawnEggItem(FightsfrightsModEntities.SHADOWCOMPANIONCOMPANION, -16777216, -13421773, new Item.Properties()));
	public static final DeferredItem<Item> MIMENTIS_SPAWN_EGG = REGISTRY.register("mimentis_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.MIMENTIS, -5522750, -11468, new Item.Properties()));
	public static final DeferredItem<Item> MIMIC_SCOWL_SPAWN_EGG = REGISTRY.register("mimic_scowl_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.MIMIC_SCOWL, -7697782, -12763843, new Item.Properties()));
	public static final DeferredItem<Item> MIMIC_BANSHAA_SPAWN_EGG = REGISTRY.register("mimic_banshaa_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.MIMIC_BANSHAA, -11711155, -13487566, new Item.Properties()));
	public static final DeferredItem<Item> MIMIC_TERRANTULA_SPAWN_EGG = REGISTRY.register("mimic_terrantula_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.MIMIC_TERRANTULA, -5000269, -7763575, new Item.Properties()));
	public static final DeferredItem<Item> MIMIC_PIONEER_SPAWN_EGG = REGISTRY.register("mimic_pioneer_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.MIMIC_PIONEER, -12961222, -12171706, new Item.Properties()));
	public static final DeferredItem<Item> MIMIC_SEER_SPAWN_EGG = REGISTRY.register("mimic_seer_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.MIMIC_SEER, -9408400, -592138, new Item.Properties()));
	public static final DeferredItem<Item> MIMIC_ALLMAN_SPAWN_EGG = REGISTRY.register("mimic_allman_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.MIMIC_ALLMAN, -12632257, -6776680, new Item.Properties()));
	public static final DeferredItem<Item> MIMIC_GRIMMSQUITO_SPAWN_EGG = REGISTRY.register("mimic_grimmsquito_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.MIMIC_GRIMMSQUITO, -11711155, -5592406, new Item.Properties()));
	public static final DeferredItem<Item> MIMIC_PATUTI_SPAWN_EGG = REGISTRY.register("mimic_patuti_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.MIMIC_PATUTI, -3289651, -9737365, new Item.Properties()));
	public static final DeferredItem<Item> MIMENTIS_CLAW = REGISTRY.register("mimentis_claw", MimentisClawItem::new);
	public static final DeferredItem<Item> MIMENTIS_CLAW_SINGLE_USE = REGISTRY.register("mimentis_claw_single_use", MimentisClawSingleUseItem::new);
	public static final DeferredItem<Item> MIME_BLOCK = block(FightsfrightsModBlocks.MIME_BLOCK);
	public static final DeferredItem<Item> SUPAI_SPAWN_EGG = REGISTRY.register("supai_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.SUPAI, -1032379, -1321141, new Item.Properties()));
	public static final DeferredItem<Item> PATHOGEN = REGISTRY.register("pathogen", PathogenItem::new);
	public static final DeferredItem<Item> ANTIDOTE = REGISTRY.register("antidote", AntidoteItem::new);
	public static final DeferredItem<Item> SYRINGE = REGISTRY.register("syringe", SyringeItem::new);
	public static final DeferredItem<Item> POISONOUS_PROBOSCIS = REGISTRY.register("poisonous_proboscis", PoisonousProboscisItem::new);
	public static final DeferredItem<Item> TERRIFYING_PROBOSCIS = REGISTRY.register("terrifying_proboscis", TerrifyingProboscisItem::new);
	public static final DeferredItem<Item> BLINDING_PROBOSCIS = REGISTRY.register("blinding_proboscis", BlindingProboscisItem::new);
	public static final DeferredItem<Item> INFECTIOUS_PROBOSCIS = REGISTRY.register("infectious_proboscis", InfectiousProboscisItem::new);
	public static final DeferredItem<Item> WITHERED_PROBOSCIS = REGISTRY.register("withered_proboscis", WitheredProboscisItem::new);
	public static final DeferredItem<Item> COCOON = block(FightsfrightsModBlocks.COCOON);
	public static final DeferredItem<Item> HIVESTONE = block(FightsfrightsModBlocks.HIVESTONE);
	public static final DeferredItem<Item> PEEPING_HIVESTONE = block(FightsfrightsModBlocks.PEEPING_HIVESTONE);
	public static final DeferredItem<Item> HIVESTONE_SLAB = block(FightsfrightsModBlocks.HIVESTONE_SLAB);
	public static final DeferredItem<Item> HIVESTONE_STAIR = block(FightsfrightsModBlocks.HIVESTONE_STAIR);
	public static final DeferredItem<Item> HIVESTONE_WALL = block(FightsfrightsModBlocks.HIVESTONE_WALL);
	public static final DeferredItem<Item> POLISHED_HIVESTONE_SLAB = block(FightsfrightsModBlocks.POLISHED_HIVESTONE_SLAB);
	public static final DeferredItem<Item> POLISHED_HIVESTONE = block(FightsfrightsModBlocks.POLISHED_HIVESTONE);
	public static final DeferredItem<Item> POLISHED_HIVESTONE_STAIRS = block(FightsfrightsModBlocks.POLISHED_HIVESTONE_STAIRS);
	public static final DeferredItem<Item> POLISHED_HIVESTONE_WALL = block(FightsfrightsModBlocks.POLISHED_HIVESTONE_WALL);
	public static final DeferredItem<Item> HIVESTONE_BRICKS = block(FightsfrightsModBlocks.HIVESTONE_BRICKS);
	public static final DeferredItem<Item> HIVESTONE_BRICKS_SLAB = block(FightsfrightsModBlocks.HIVESTONE_BRICKS_SLAB);
	public static final DeferredItem<Item> HIVESTONE_BRICKS_STAIRS = block(FightsfrightsModBlocks.HIVESTONE_BRICKS_STAIRS);
	public static final DeferredItem<Item> HIVESTONE_BRICKS_WALL = block(FightsfrightsModBlocks.HIVESTONE_BRICKS_WALL);
	public static final DeferredItem<Item> CHISELED_HIVESTONE = block(FightsfrightsModBlocks.CHISELED_HIVESTONE);
	public static final DeferredItem<Item> DREAMCATCHER = block(FightsfrightsModBlocks.DREAMCATCHER);
	public static final DeferredItem<Item> CHITIN = REGISTRY.register("chitin", ChitinItem::new);
	public static final DeferredItem<Item> CHITINBLOCK = block(FightsfrightsModBlocks.CHITINBLOCK);
	public static final DeferredItem<Item> SMOOTHCHITIN = block(FightsfrightsModBlocks.SMOOTHCHITIN);
	public static final DeferredItem<Item> CHITINBRICKS = block(FightsfrightsModBlocks.CHITINBRICKS);
	public static final DeferredItem<Item> SMOOTHCHITINSLABS = block(FightsfrightsModBlocks.SMOOTHCHITINSLABS);
	public static final DeferredItem<Item> SMOOTH_CHITIN_STAIRS = block(FightsfrightsModBlocks.SMOOTH_CHITIN_STAIRS);
	public static final DeferredItem<Item> SMOOTH_CHITIN_WALL = block(FightsfrightsModBlocks.SMOOTH_CHITIN_WALL);
	public static final DeferredItem<Item> CHITINBRICKSSLAB = block(FightsfrightsModBlocks.CHITINBRICKSSLAB);
	public static final DeferredItem<Item> CHITINBRICKSSTAIRS = block(FightsfrightsModBlocks.CHITINBRICKSSTAIRS);
	public static final DeferredItem<Item> CHITINBRICKSWALL = block(FightsfrightsModBlocks.CHITINBRICKSWALL);
	public static final DeferredItem<Item> CHISELED_CHITIN = block(FightsfrightsModBlocks.CHISELED_CHITIN);
	public static final DeferredItem<Item> OMINOUS_PLATE = REGISTRY.register("ominous_plate", OminousPlateItem::new);
	public static final DeferredItem<Item> NIGHTMARE = REGISTRY.register("nightmare", NightmareItem::new);
	public static final DeferredItem<Item> OMINOUS_ESSENCE = REGISTRY.register("ominous_essence", OminousEssenceItem::new);
	public static final DeferredItem<Item> OMINOUS_ARMOR_HELMET = REGISTRY.register("ominous_armor_helmet", OminousArmorItem.Helmet::new);
	public static final DeferredItem<Item> OMINOUS_ARMOR_CHESTPLATE = REGISTRY.register("ominous_armor_chestplate", OminousArmorItem.Chestplate::new);
	public static final DeferredItem<Item> OMINOUS_ARMOR_LEGGINGS = REGISTRY.register("ominous_armor_leggings", OminousArmorItem.Leggings::new);
	public static final DeferredItem<Item> OMINOUS_ARMOR_BOOTS = REGISTRY.register("ominous_armor_boots", OminousArmorItem.Boots::new);
	public static final DeferredItem<Item> MYSTERYBLOCK = block(FightsfrightsModBlocks.MYSTERYBLOCK);
	public static final DeferredItem<Item> OMINOUS_PLATE_BLOCK = block(FightsfrightsModBlocks.OMINOUS_PLATE_BLOCK);
	public static final DeferredItem<Item> JELLY_BLOCK = block(FightsfrightsModBlocks.JELLY_BLOCK);
	public static final DeferredItem<Item> SMOOTH_JELLY = block(FightsfrightsModBlocks.SMOOTH_JELLY);
	public static final DeferredItem<Item> SMOOTH_JELLY_SLAB = block(FightsfrightsModBlocks.SMOOTH_JELLY_SLAB);
	public static final DeferredItem<Item> SMOOTH_JELLY_STAIRS = block(FightsfrightsModBlocks.SMOOTH_JELLY_STAIRS);
	public static final DeferredItem<Item> SMOOTH_JELLY_WALL = block(FightsfrightsModBlocks.SMOOTH_JELLY_WALL);
	public static final DeferredItem<Item> JELLY_BRICKS = block(FightsfrightsModBlocks.JELLY_BRICKS);
	public static final DeferredItem<Item> JELLY_BRICKS_SLAB = block(FightsfrightsModBlocks.JELLY_BRICKS_SLAB);
	public static final DeferredItem<Item> JELLY_BRICKS_STAIRS = block(FightsfrightsModBlocks.JELLY_BRICKS_STAIRS);
	public static final DeferredItem<Item> JELLY_BRICKS_WALL = block(FightsfrightsModBlocks.JELLY_BRICKS_WALL);
	public static final DeferredItem<Item> CHISELED_JELLY = block(FightsfrightsModBlocks.CHISELED_JELLY);
	public static final DeferredItem<Item> MONSTROUS_PLATE_BLOCK = block(FightsfrightsModBlocks.MONSTROUS_PLATE_BLOCK);
	public static final DeferredItem<Item> TRASHCAN = block(FightsfrightsModBlocks.TRASHCAN);
	public static final DeferredItem<Item> SLOP = block(FightsfrightsModBlocks.SLOP);
	public static final DeferredItem<Item> NETHER_BANSHAA_SPAWN_EGG = REGISTRY.register("nether_banshaa_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.NETHER_BANSHAA, -2630683, -6772262, new Item.Properties()));
	public static final DeferredItem<Item> CIRCUIT_LEVER = block(FightsfrightsModBlocks.CIRCUIT_LEVER);
	public static final DeferredItem<Item> REDSTONE_DISPLAY = block(FightsfrightsModBlocks.REDSTONE_DISPLAY);
	public static final DeferredItem<Item> NETHERSILVERFISH_SPAWN_EGG = REGISTRY.register("nethersilverfish_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.NETHERSILVERFISH, -6727090, -8431794, new Item.Properties()));
	public static final DeferredItem<Item> NETHER_SPIDER_SPAWN_EGG = REGISTRY.register("nether_spider_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.NETHER_SPIDER, -12634848, -6205403, new Item.Properties()));
	public static final DeferredItem<Item> NETHERCAVESPIDER_SPAWN_EGG = REGISTRY.register("nethercavespider_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.NETHERCAVESPIDER, -10275287, -1755557, new Item.Properties()));
	public static final DeferredItem<Item> MIMIC_BEETLES_SPAWN_EGG = REGISTRY.register("mimic_beetles_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.MIMIC_BEETLES, -6710887, -3355444, new Item.Properties()));
	public static final DeferredItem<Item> FIRE_SWARM_SPAWN_EGG = REGISTRY.register("fire_swarm_spawn_egg", () -> new DeferredSpawnEggItem(FightsfrightsModEntities.FIRE_SWARM, -1609964, -808960, new Item.Properties()));

	// Start of user code block custom items
	// End of user code block custom items
	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
