
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.fightsfrights.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.fightsfrights.block.VSDBlock;
import net.mcreator.fightsfrights.block.TrashcanBlock;
import net.mcreator.fightsfrights.block.TotemBlockBlock;
import net.mcreator.fightsfrights.block.SmoothchitinslabsBlock;
import net.mcreator.fightsfrights.block.SmoothchitinBlock;
import net.mcreator.fightsfrights.block.SmoothJellyWallBlock;
import net.mcreator.fightsfrights.block.SmoothJellyStairsBlock;
import net.mcreator.fightsfrights.block.SmoothJellySlabBlock;
import net.mcreator.fightsfrights.block.SmoothJellyBlock;
import net.mcreator.fightsfrights.block.SmoothChitinWallBlock;
import net.mcreator.fightsfrights.block.SmoothChitinStairsBlock;
import net.mcreator.fightsfrights.block.SlopBlock;
import net.mcreator.fightsfrights.block.RottenBlockBlock;
import net.mcreator.fightsfrights.block.RedstoneDisplayBlock;
import net.mcreator.fightsfrights.block.PolishedHivestoneWallBlock;
import net.mcreator.fightsfrights.block.PolishedHivestoneStairsBlock;
import net.mcreator.fightsfrights.block.PolishedHivestoneSlabBlock;
import net.mcreator.fightsfrights.block.PolishedHivestoneBlock;
import net.mcreator.fightsfrights.block.PeepingHivestoneBlock;
import net.mcreator.fightsfrights.block.OminousPlateBlockBlock;
import net.mcreator.fightsfrights.block.MysteryblockBlock;
import net.mcreator.fightsfrights.block.MonstrousPlateBlockBlock;
import net.mcreator.fightsfrights.block.MimeBlockBlock;
import net.mcreator.fightsfrights.block.JellyBricksWallBlock;
import net.mcreator.fightsfrights.block.JellyBricksStairsBlock;
import net.mcreator.fightsfrights.block.JellyBricksSlabBlock;
import net.mcreator.fightsfrights.block.JellyBricksBlock;
import net.mcreator.fightsfrights.block.JellyBlockBlock;
import net.mcreator.fightsfrights.block.HivestoneWallBlock;
import net.mcreator.fightsfrights.block.HivestoneStairBlock;
import net.mcreator.fightsfrights.block.HivestoneSlabBlock;
import net.mcreator.fightsfrights.block.HivestoneBricksWallBlock;
import net.mcreator.fightsfrights.block.HivestoneBricksStairsBlock;
import net.mcreator.fightsfrights.block.HivestoneBricksSlabBlock;
import net.mcreator.fightsfrights.block.HivestoneBricksBlock;
import net.mcreator.fightsfrights.block.HivestoneBlock;
import net.mcreator.fightsfrights.block.HexblockBlock;
import net.mcreator.fightsfrights.block.FissuredNetherrackBlock;
import net.mcreator.fightsfrights.block.EmptyHexBlockBlock;
import net.mcreator.fightsfrights.block.DreamcatcherBlock;
import net.mcreator.fightsfrights.block.DarkTramaBlock;
import net.mcreator.fightsfrights.block.CrusherBlock;
import net.mcreator.fightsfrights.block.CocoonBlock;
import net.mcreator.fightsfrights.block.CircuitLeverBlock;
import net.mcreator.fightsfrights.block.ChitinbrickswallBlock;
import net.mcreator.fightsfrights.block.ChitinbricksstairsBlock;
import net.mcreator.fightsfrights.block.ChitinbricksslabBlock;
import net.mcreator.fightsfrights.block.ChitinbricksBlock;
import net.mcreator.fightsfrights.block.ChitinblockBlock;
import net.mcreator.fightsfrights.block.ChiseledJellyBlock;
import net.mcreator.fightsfrights.block.ChiseledHivestoneBlock;
import net.mcreator.fightsfrights.block.ChiseledChitinBlock;
import net.mcreator.fightsfrights.block.BllightCapBlockBlock;
import net.mcreator.fightsfrights.block.BlightdoorBlock;
import net.mcreator.fightsfrights.block.BlightcapBlock;
import net.mcreator.fightsfrights.block.BlightTrapdoorBlock;
import net.mcreator.fightsfrights.block.BlightStemBlock;
import net.mcreator.fightsfrights.block.BlightStairsBlock;
import net.mcreator.fightsfrights.block.BlightSlabBlock;
import net.mcreator.fightsfrights.block.BlightPlanksBlock;
import net.mcreator.fightsfrights.block.BlightHyphaeBlock;
import net.mcreator.fightsfrights.block.BlightFencegateBlock;
import net.mcreator.fightsfrights.block.BlightFenceBlock;
import net.mcreator.fightsfrights.block.BlightButtonBlock;
import net.mcreator.fightsfrights.FightsfrightsMod;

public class FightsfrightsModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, FightsfrightsMod.MODID);
	public static final RegistryObject<Block> ROTTEN_BLOCK = REGISTRY.register("rotten_block", () -> new RottenBlockBlock());
	public static final RegistryObject<Block> TOTEM_BLOCK = REGISTRY.register("totem_block", () -> new TotemBlockBlock());
	public static final RegistryObject<Block> EMPTY_HEX_BLOCK = REGISTRY.register("empty_hex_block", () -> new EmptyHexBlockBlock());
	public static final RegistryObject<Block> HEXBLOCK = REGISTRY.register("hexblock", () -> new HexblockBlock());
	public static final RegistryObject<Block> BLIGHT_STEM = REGISTRY.register("blight_stem", () -> new BlightStemBlock());
	public static final RegistryObject<Block> BLLIGHT_CAP_BLOCK = REGISTRY.register("bllight_cap_block", () -> new BllightCapBlockBlock());
	public static final RegistryObject<Block> BLIGHTCAP = REGISTRY.register("blightcap", () -> new BlightcapBlock());
	public static final RegistryObject<Block> DARK_TRAMA = REGISTRY.register("dark_trama", () -> new DarkTramaBlock());
	public static final RegistryObject<Block> BLIGHT_PLANKS = REGISTRY.register("blight_planks", () -> new BlightPlanksBlock());
	public static final RegistryObject<Block> BLIGHT_HYPHAE = REGISTRY.register("blight_hyphae", () -> new BlightHyphaeBlock());
	public static final RegistryObject<Block> BLIGHT_STAIRS = REGISTRY.register("blight_stairs", () -> new BlightStairsBlock());
	public static final RegistryObject<Block> BLIGHT_SLAB = REGISTRY.register("blight_slab", () -> new BlightSlabBlock());
	public static final RegistryObject<Block> BLIGHT_FENCE = REGISTRY.register("blight_fence", () -> new BlightFenceBlock());
	public static final RegistryObject<Block> BLIGHT_FENCEGATE = REGISTRY.register("blight_fencegate", () -> new BlightFencegateBlock());
	public static final RegistryObject<Block> BLIGHT_BUTTON = REGISTRY.register("blight_button", () -> new BlightButtonBlock());
	public static final RegistryObject<Block> BLIGHT_TRAPDOOR = REGISTRY.register("blight_trapdoor", () -> new BlightTrapdoorBlock());
	public static final RegistryObject<Block> BLIGHTDOOR = REGISTRY.register("blightdoor", () -> new BlightdoorBlock());
	public static final RegistryObject<Block> CRUSHER = REGISTRY.register("crusher", () -> new CrusherBlock());
	public static final RegistryObject<Block> VSD = REGISTRY.register("vsd", () -> new VSDBlock());
	public static final RegistryObject<Block> FISSURED_NETHERRACK = REGISTRY.register("fissured_netherrack", () -> new FissuredNetherrackBlock());
	public static final RegistryObject<Block> MIME_BLOCK = REGISTRY.register("mime_block", () -> new MimeBlockBlock());
	public static final RegistryObject<Block> COCOON = REGISTRY.register("cocoon", () -> new CocoonBlock());
	public static final RegistryObject<Block> HIVESTONE = REGISTRY.register("hivestone", () -> new HivestoneBlock());
	public static final RegistryObject<Block> PEEPING_HIVESTONE = REGISTRY.register("peeping_hivestone", () -> new PeepingHivestoneBlock());
	public static final RegistryObject<Block> HIVESTONE_SLAB = REGISTRY.register("hivestone_slab", () -> new HivestoneSlabBlock());
	public static final RegistryObject<Block> HIVESTONE_STAIR = REGISTRY.register("hivestone_stair", () -> new HivestoneStairBlock());
	public static final RegistryObject<Block> HIVESTONE_WALL = REGISTRY.register("hivestone_wall", () -> new HivestoneWallBlock());
	public static final RegistryObject<Block> POLISHED_HIVESTONE_SLAB = REGISTRY.register("polished_hivestone_slab", () -> new PolishedHivestoneSlabBlock());
	public static final RegistryObject<Block> POLISHED_HIVESTONE = REGISTRY.register("polished_hivestone", () -> new PolishedHivestoneBlock());
	public static final RegistryObject<Block> POLISHED_HIVESTONE_STAIRS = REGISTRY.register("polished_hivestone_stairs", () -> new PolishedHivestoneStairsBlock());
	public static final RegistryObject<Block> POLISHED_HIVESTONE_WALL = REGISTRY.register("polished_hivestone_wall", () -> new PolishedHivestoneWallBlock());
	public static final RegistryObject<Block> HIVESTONE_BRICKS = REGISTRY.register("hivestone_bricks", () -> new HivestoneBricksBlock());
	public static final RegistryObject<Block> HIVESTONE_BRICKS_SLAB = REGISTRY.register("hivestone_bricks_slab", () -> new HivestoneBricksSlabBlock());
	public static final RegistryObject<Block> HIVESTONE_BRICKS_STAIRS = REGISTRY.register("hivestone_bricks_stairs", () -> new HivestoneBricksStairsBlock());
	public static final RegistryObject<Block> HIVESTONE_BRICKS_WALL = REGISTRY.register("hivestone_bricks_wall", () -> new HivestoneBricksWallBlock());
	public static final RegistryObject<Block> CHISELED_HIVESTONE = REGISTRY.register("chiseled_hivestone", () -> new ChiseledHivestoneBlock());
	public static final RegistryObject<Block> DREAMCATCHER = REGISTRY.register("dreamcatcher", () -> new DreamcatcherBlock());
	public static final RegistryObject<Block> CHITINBLOCK = REGISTRY.register("chitinblock", () -> new ChitinblockBlock());
	public static final RegistryObject<Block> SMOOTHCHITIN = REGISTRY.register("smoothchitin", () -> new SmoothchitinBlock());
	public static final RegistryObject<Block> CHITINBRICKS = REGISTRY.register("chitinbricks", () -> new ChitinbricksBlock());
	public static final RegistryObject<Block> SMOOTHCHITINSLABS = REGISTRY.register("smoothchitinslabs", () -> new SmoothchitinslabsBlock());
	public static final RegistryObject<Block> SMOOTH_CHITIN_STAIRS = REGISTRY.register("smooth_chitin_stairs", () -> new SmoothChitinStairsBlock());
	public static final RegistryObject<Block> SMOOTH_CHITIN_WALL = REGISTRY.register("smooth_chitin_wall", () -> new SmoothChitinWallBlock());
	public static final RegistryObject<Block> CHITINBRICKSSLAB = REGISTRY.register("chitinbricksslab", () -> new ChitinbricksslabBlock());
	public static final RegistryObject<Block> CHITINBRICKSSTAIRS = REGISTRY.register("chitinbricksstairs", () -> new ChitinbricksstairsBlock());
	public static final RegistryObject<Block> CHITINBRICKSWALL = REGISTRY.register("chitinbrickswall", () -> new ChitinbrickswallBlock());
	public static final RegistryObject<Block> CHISELED_CHITIN = REGISTRY.register("chiseled_chitin", () -> new ChiseledChitinBlock());
	public static final RegistryObject<Block> MYSTERYBLOCK = REGISTRY.register("mysteryblock", () -> new MysteryblockBlock());
	public static final RegistryObject<Block> OMINOUS_PLATE_BLOCK = REGISTRY.register("ominous_plate_block", () -> new OminousPlateBlockBlock());
	public static final RegistryObject<Block> JELLY_BLOCK = REGISTRY.register("jelly_block", () -> new JellyBlockBlock());
	public static final RegistryObject<Block> SMOOTH_JELLY = REGISTRY.register("smooth_jelly", () -> new SmoothJellyBlock());
	public static final RegistryObject<Block> SMOOTH_JELLY_SLAB = REGISTRY.register("smooth_jelly_slab", () -> new SmoothJellySlabBlock());
	public static final RegistryObject<Block> SMOOTH_JELLY_STAIRS = REGISTRY.register("smooth_jelly_stairs", () -> new SmoothJellyStairsBlock());
	public static final RegistryObject<Block> SMOOTH_JELLY_WALL = REGISTRY.register("smooth_jelly_wall", () -> new SmoothJellyWallBlock());
	public static final RegistryObject<Block> JELLY_BRICKS = REGISTRY.register("jelly_bricks", () -> new JellyBricksBlock());
	public static final RegistryObject<Block> JELLY_BRICKS_SLAB = REGISTRY.register("jelly_bricks_slab", () -> new JellyBricksSlabBlock());
	public static final RegistryObject<Block> JELLY_BRICKS_STAIRS = REGISTRY.register("jelly_bricks_stairs", () -> new JellyBricksStairsBlock());
	public static final RegistryObject<Block> JELLY_BRICKS_WALL = REGISTRY.register("jelly_bricks_wall", () -> new JellyBricksWallBlock());
	public static final RegistryObject<Block> CHISELED_JELLY = REGISTRY.register("chiseled_jelly", () -> new ChiseledJellyBlock());
	public static final RegistryObject<Block> MONSTROUS_PLATE_BLOCK = REGISTRY.register("monstrous_plate_block", () -> new MonstrousPlateBlockBlock());
	public static final RegistryObject<Block> TRASHCAN = REGISTRY.register("trashcan", () -> new TrashcanBlock());
	public static final RegistryObject<Block> SLOP = REGISTRY.register("slop", () -> new SlopBlock());
	public static final RegistryObject<Block> CIRCUIT_LEVER = REGISTRY.register("circuit_lever", () -> new CircuitLeverBlock());
	public static final RegistryObject<Block> REDSTONE_DISPLAY = REGISTRY.register("redstone_display", () -> new RedstoneDisplayBlock());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
