
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.fightsfrights.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.fightsfrights.item.WitheredProboscisItem;
import net.mcreator.fightsfrights.item.UltimateMethodUpdatedItem;
import net.mcreator.fightsfrights.item.TerrifyingProboscisItem;
import net.mcreator.fightsfrights.item.TerrantulaLegItem;
import net.mcreator.fightsfrights.item.SyringeItem;
import net.mcreator.fightsfrights.item.ShackleItem;
import net.mcreator.fightsfrights.item.RottenHandleItem;
import net.mcreator.fightsfrights.item.RavagerHornItem;
import net.mcreator.fightsfrights.item.PutridScythe2Item;
import net.mcreator.fightsfrights.item.PungentSoupItem;
import net.mcreator.fightsfrights.item.PoisonousProboscisItem;
import net.mcreator.fightsfrights.item.PoisonOrbItemItem;
import net.mcreator.fightsfrights.item.PathogenItem;
import net.mcreator.fightsfrights.item.OminousTuskItem;
import net.mcreator.fightsfrights.item.OminousScepterItem;
import net.mcreator.fightsfrights.item.OminousPlateItem;
import net.mcreator.fightsfrights.item.OminousEssenceItem;
import net.mcreator.fightsfrights.item.OminousBottleItem;
import net.mcreator.fightsfrights.item.OminousArmorItem;
import net.mcreator.fightsfrights.item.NightmareItem;
import net.mcreator.fightsfrights.item.MonstruousPlateItem;
import net.mcreator.fightsfrights.item.MonstrousArmorItem;
import net.mcreator.fightsfrights.item.MonsterSaladItem;
import net.mcreator.fightsfrights.item.MonsterPopItem;
import net.mcreator.fightsfrights.item.MimicBeetleItem;
import net.mcreator.fightsfrights.item.MimentisClawSingleUseItem;
import net.mcreator.fightsfrights.item.MimentisClawItem;
import net.mcreator.fightsfrights.item.InfectiousProboscisItem;
import net.mcreator.fightsfrights.item.HexItem;
import net.mcreator.fightsfrights.item.GoopItem;
import net.mcreator.fightsfrights.item.GoldenTongueItem;
import net.mcreator.fightsfrights.item.GillsItem;
import net.mcreator.fightsfrights.item.ForewingsItem;
import net.mcreator.fightsfrights.item.EmptyHexItem;
import net.mcreator.fightsfrights.item.ElderSpineItem;
import net.mcreator.fightsfrights.item.DeadsteelScimitarItem;
import net.mcreator.fightsfrights.item.ChitinItem;
import net.mcreator.fightsfrights.item.ChipItem;
import net.mcreator.fightsfrights.item.CheeseStickItem;
import net.mcreator.fightsfrights.item.ChargedScrapItem;
import net.mcreator.fightsfrights.item.ChargedFleshItem;
import net.mcreator.fightsfrights.item.ChargedChiliItem;
import net.mcreator.fightsfrights.item.BugDustItem;
import net.mcreator.fightsfrights.item.BluntJavelinItem;
import net.mcreator.fightsfrights.item.BlindingProboscisItem;
import net.mcreator.fightsfrights.item.BanshaasLungsItem;
import net.mcreator.fightsfrights.item.AntidoteItem;
import net.mcreator.fightsfrights.item.AllbombItem;
import net.mcreator.fightsfrights.FightsfrightsMod;

public class FightsfrightsModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, FightsfrightsMod.MODID);
	public static final RegistryObject<Item> ALLMAN_SPAWN_EGG = REGISTRY.register("allman_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.ALLMAN, -12702429, -8875630, new Item.Properties()));
	public static final RegistryObject<Item> SCOWL_SPAWN_EGG = REGISTRY.register("scowl_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.SCOWL, -9399763, -10079488, new Item.Properties()));
	public static final RegistryObject<Item> SHACKLE = REGISTRY.register("shackle", () -> new ShackleItem());
	public static final RegistryObject<Item> ROTTEN_HANDLE = REGISTRY.register("rotten_handle", () -> new RottenHandleItem());
	public static final RegistryObject<Item> GOLDEN_TONGUE = REGISTRY.register("golden_tongue", () -> new GoldenTongueItem());
	public static final RegistryObject<Item> GOOP = REGISTRY.register("goop", () -> new GoopItem());
	public static final RegistryObject<Item> MONSTER_POP = REGISTRY.register("monster_pop", () -> new MonsterPopItem());
	public static final RegistryObject<Item> SEER_SPAWN_EGG = REGISTRY.register("seer_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.SEER, -14264977, -13966086, new Item.Properties()));
	public static final RegistryObject<Item> PATUTI_SPAWN_EGG = REGISTRY.register("patuti_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.PATUTI, -8992319, -12967067, new Item.Properties()));
	public static final RegistryObject<Item> GILLS = REGISTRY.register("gills", () -> new GillsItem());
	public static final RegistryObject<Item> PIONEER_SPAWN_EGG = REGISTRY.register("pioneer_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.PIONEER, -15658479, -14031283, new Item.Properties()));
	public static final RegistryObject<Item> CHIP = REGISTRY.register("chip", () -> new ChipItem());
	public static final RegistryObject<Item> TERRANTULA_SPAWN_EGG = REGISTRY.register("terrantula_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.TERRANTULA, -5477120, -8370416, new Item.Properties()));
	public static final RegistryObject<Item> TERRANTULA_LEG = REGISTRY.register("terrantula_leg", () -> new TerrantulaLegItem());
	public static final RegistryObject<Item> BANSHAA_SPAWN_EGG = REGISTRY.register("banshaa_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.BANSHAA, -2630683, -6772262, new Item.Properties()));
	public static final RegistryObject<Item> BANSHAAS_LUNGS = REGISTRY.register("banshaas_lungs", () -> new BanshaasLungsItem());
	public static final RegistryObject<Item> MONSTER_SALAD = REGISTRY.register("monster_salad", () -> new MonsterSaladItem());
	public static final RegistryObject<Item> ROTTEN_BLOCK = block(FightsfrightsModBlocks.ROTTEN_BLOCK);
	public static final RegistryObject<Item> TOTEM_BLOCK = block(FightsfrightsModBlocks.TOTEM_BLOCK);
	public static final RegistryObject<Item> EMPTY_HEX_BLOCK = block(FightsfrightsModBlocks.EMPTY_HEX_BLOCK);
	public static final RegistryObject<Item> HEX = REGISTRY.register("hex", () -> new HexItem());
	public static final RegistryObject<Item> EMPTY_HEX = REGISTRY.register("empty_hex", () -> new EmptyHexItem());
	public static final RegistryObject<Item> OMINOUS_BOTTLE = REGISTRY.register("ominous_bottle", () -> new OminousBottleItem());
	public static final RegistryObject<Item> HEXBLOCK = block(FightsfrightsModBlocks.HEXBLOCK);
	public static final RegistryObject<Item> RAVAGER_HORN = REGISTRY.register("ravager_horn", () -> new RavagerHornItem());
	public static final RegistryObject<Item> ELDER_SPINE = REGISTRY.register("elder_spine", () -> new ElderSpineItem());
	public static final RegistryObject<Item> MONSTRUOUS_PLATE = REGISTRY.register("monstruous_plate", () -> new MonstruousPlateItem());
	public static final RegistryObject<Item> MONSTROUS_ARMOR_HELMET = REGISTRY.register("monstrous_armor_helmet", () -> new MonstrousArmorItem.Helmet());
	public static final RegistryObject<Item> MONSTROUS_ARMOR_CHESTPLATE = REGISTRY.register("monstrous_armor_chestplate", () -> new MonstrousArmorItem.Chestplate());
	public static final RegistryObject<Item> MONSTROUS_ARMOR_LEGGINGS = REGISTRY.register("monstrous_armor_leggings", () -> new MonstrousArmorItem.Leggings());
	public static final RegistryObject<Item> MONSTROUS_ARMOR_BOOTS = REGISTRY.register("monstrous_armor_boots", () -> new MonstrousArmorItem.Boots());
	public static final RegistryObject<Item> BLIGHT_STEM = block(FightsfrightsModBlocks.BLIGHT_STEM);
	public static final RegistryObject<Item> BLLIGHT_CAP_BLOCK = block(FightsfrightsModBlocks.BLLIGHT_CAP_BLOCK);
	public static final RegistryObject<Item> BLIGHTCAP = block(FightsfrightsModBlocks.BLIGHTCAP);
	public static final RegistryObject<Item> DARK_TRAMA = block(FightsfrightsModBlocks.DARK_TRAMA);
	public static final RegistryObject<Item> BLIGHT_PLANKS = block(FightsfrightsModBlocks.BLIGHT_PLANKS);
	public static final RegistryObject<Item> BLIGHT_HYPHAE = block(FightsfrightsModBlocks.BLIGHT_HYPHAE);
	public static final RegistryObject<Item> BLIGHT_STAIRS = block(FightsfrightsModBlocks.BLIGHT_STAIRS);
	public static final RegistryObject<Item> BLIGHT_SLAB = block(FightsfrightsModBlocks.BLIGHT_SLAB);
	public static final RegistryObject<Item> BLIGHT_FENCE = block(FightsfrightsModBlocks.BLIGHT_FENCE);
	public static final RegistryObject<Item> BLIGHT_FENCEGATE = block(FightsfrightsModBlocks.BLIGHT_FENCEGATE);
	public static final RegistryObject<Item> BLIGHT_BUTTON = block(FightsfrightsModBlocks.BLIGHT_BUTTON);
	public static final RegistryObject<Item> BLIGHT_TRAPDOOR = block(FightsfrightsModBlocks.BLIGHT_TRAPDOOR);
	public static final RegistryObject<Item> BLIGHTDOOR = doubleBlock(FightsfrightsModBlocks.BLIGHTDOOR);
	public static final RegistryObject<Item> CRUSHER = block(FightsfrightsModBlocks.CRUSHER);
	public static final RegistryObject<Item> REANIMATED_SPAWN_EGG = REGISTRY.register("reanimated_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.REANIMATED, -4035764, -1579109, new Item.Properties()));
	public static final RegistryObject<Item> CHARGED_SCRAP = REGISTRY.register("charged_scrap", () -> new ChargedScrapItem());
	public static final RegistryObject<Item> CHARGED_FLESH = REGISTRY.register("charged_flesh", () -> new ChargedFleshItem());
	public static final RegistryObject<Item> GHASTLY_GENERAL_SPAWN_EGG = REGISTRY.register("ghastly_general_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.GHASTLY_GENERAL, -13884353, -65425, new Item.Properties()));
	public static final RegistryObject<Item> POISON_ORB_ITEM = REGISTRY.register("poison_orb_item", () -> new PoisonOrbItemItem());
	public static final RegistryObject<Item> DEADSTEEL_SCIMITAR = REGISTRY.register("deadsteel_scimitar", () -> new DeadsteelScimitarItem());
	public static final RegistryObject<Item> PUTRID_SCYTHE_2 = REGISTRY.register("putrid_scythe_2", () -> new PutridScythe2Item());
	public static final RegistryObject<Item> SHACKLED_SPAWN_EGG = REGISTRY.register("shackled_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.SHACKLED, -2958626, -8875630, new Item.Properties()));
	public static final RegistryObject<Item> ALLBOMB = REGISTRY.register("allbomb", () -> new AllbombItem());
	public static final RegistryObject<Item> PIGLIN_PROSECUTOR_SPAWN_EGG = REGISTRY.register("piglin_prosecutor_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.PIGLIN_PROSECUTOR, -1531788, -65425, new Item.Properties()));
	public static final RegistryObject<Item> BLUNT_JAVELIN = REGISTRY.register("blunt_javelin", () -> new BluntJavelinItem());
	public static final RegistryObject<Item> PUNGENT_SOUP = REGISTRY.register("pungent_soup", () -> new PungentSoupItem());
	public static final RegistryObject<Item> OMINOUS_TUSK = REGISTRY.register("ominous_tusk", () -> new OminousTuskItem());
	public static final RegistryObject<Item> IMPERIAL_ILLAGER_P_1_SPAWN_EGG = REGISTRY.register("imperial_illager_p_1_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.IMPERIAL_ILLAGER_P_1, -8220261, -65425, new Item.Properties()));
	public static final RegistryObject<Item> IMPERIAL_ILLAGER_P_2_SPAWN_EGG = REGISTRY.register("imperial_illager_p_2_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.IMPERIAL_ILLAGER_P_2, -13808286, -65425, new Item.Properties()));
	public static final RegistryObject<Item> OMINOUS_SCEPTER = REGISTRY.register("ominous_scepter", () -> new OminousScepterItem());
	public static final RegistryObject<Item> EFFIGY_SPAWN_EGG = REGISTRY.register("effigy_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.EFFIGY, -665046, -9448139, new Item.Properties()));
	public static final RegistryObject<Item> VSD = block(FightsfrightsModBlocks.VSD);
	public static final RegistryObject<Item> CHARGED_CHILI = REGISTRY.register("charged_chili", () -> new ChargedChiliItem());
	public static final RegistryObject<Item> CHEESE_STICK = REGISTRY.register("cheese_stick", () -> new CheeseStickItem());
	public static final RegistryObject<Item> WICKE_WARMONGER_SPAWN_EGG = REGISTRY.register("wicke_warmonger_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.WICKE_WARMONGER, -16724737, -65425, new Item.Properties()));
	public static final RegistryObject<Item> FISSURED_NETHERRACK = block(FightsfrightsModBlocks.FISSURED_NETHERRACK);
	public static final RegistryObject<Item> MALICIOUS_MONARCH_P_1_SPAWN_EGG = REGISTRY.register("malicious_monarch_p_1_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.MALICIOUS_MONARCH_P_1, -458497, -65425, new Item.Properties()));
	public static final RegistryObject<Item> MALICIOUS_MONARCH_P_2_SPAWN_EGG = REGISTRY.register("malicious_monarch_p_2_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.MALICIOUS_MONARCH_P_2, -55058, -65425, new Item.Properties()));
	public static final RegistryObject<Item> CALLOUS_COMMANDER_1_SPAWN_EGG = REGISTRY.register("callous_commander_1_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.CALLOUS_COMMANDER_1, -13828343, -65425, new Item.Properties()));
	public static final RegistryObject<Item> ULTIMATE_METHOD_UPDATED = REGISTRY.register("ultimate_method_updated", () -> new UltimateMethodUpdatedItem());
	public static final RegistryObject<Item> MIMIC_BEETLE = REGISTRY.register("mimic_beetle", () -> new MimicBeetleItem());
	public static final RegistryObject<Item> GRIMMSQUITO_SPAWN_EGG = REGISTRY.register("grimmsquito_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.GRIMMSQUITO, -12116201, -5043164, new Item.Properties()));
	public static final RegistryObject<Item> FOREWINGS = REGISTRY.register("forewings", () -> new ForewingsItem());
	public static final RegistryObject<Item> BUG_DUST = REGISTRY.register("bug_dust", () -> new BugDustItem());
	public static final RegistryObject<Item> SHADOW_SPAWN_EGG = REGISTRY.register("shadow_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.SHADOW, -16777216, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> SHADOWCOMPANION_SPAWN_EGG = REGISTRY.register("shadowcompanion_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.SHADOWCOMPANION, -16777216, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> SHADOWCOMPANIONCOMPANION_SPAWN_EGG = REGISTRY.register("shadowcompanioncompanion_spawn_egg",
			() -> new ForgeSpawnEggItem(FightsfrightsModEntities.SHADOWCOMPANIONCOMPANION, -16777216, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> MIMENTIS_SPAWN_EGG = REGISTRY.register("mimentis_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.MIMENTIS, -5522750, -11468, new Item.Properties()));
	public static final RegistryObject<Item> MIMIC_SCOWL_SPAWN_EGG = REGISTRY.register("mimic_scowl_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.MIMIC_SCOWL, -7697782, -12763843, new Item.Properties()));
	public static final RegistryObject<Item> MIMIC_BANSHAA_SPAWN_EGG = REGISTRY.register("mimic_banshaa_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.MIMIC_BANSHAA, -11711155, -13487566, new Item.Properties()));
	public static final RegistryObject<Item> MIMIC_TERRANTULA_SPAWN_EGG = REGISTRY.register("mimic_terrantula_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.MIMIC_TERRANTULA, -5000269, -7763575, new Item.Properties()));
	public static final RegistryObject<Item> MIMIC_PIONEER_SPAWN_EGG = REGISTRY.register("mimic_pioneer_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.MIMIC_PIONEER, -12961222, -12171706, new Item.Properties()));
	public static final RegistryObject<Item> MIMIC_SEER_SPAWN_EGG = REGISTRY.register("mimic_seer_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.MIMIC_SEER, -9408400, -592138, new Item.Properties()));
	public static final RegistryObject<Item> MIMIC_ALLMAN_SPAWN_EGG = REGISTRY.register("mimic_allman_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.MIMIC_ALLMAN, -12632257, -6776680, new Item.Properties()));
	public static final RegistryObject<Item> MIMIC_GRIMMSQUITO_SPAWN_EGG = REGISTRY.register("mimic_grimmsquito_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.MIMIC_GRIMMSQUITO, -11711155, -5592406, new Item.Properties()));
	public static final RegistryObject<Item> MIMIC_PATUTI_SPAWN_EGG = REGISTRY.register("mimic_patuti_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.MIMIC_PATUTI, -3289651, -9737365, new Item.Properties()));
	public static final RegistryObject<Item> MIMENTIS_CLAW = REGISTRY.register("mimentis_claw", () -> new MimentisClawItem());
	public static final RegistryObject<Item> MIMENTIS_CLAW_SINGLE_USE = REGISTRY.register("mimentis_claw_single_use", () -> new MimentisClawSingleUseItem());
	public static final RegistryObject<Item> MIME_BLOCK = block(FightsfrightsModBlocks.MIME_BLOCK);
	public static final RegistryObject<Item> SUPAI_SPAWN_EGG = REGISTRY.register("supai_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.SUPAI, -1032379, -1321141, new Item.Properties()));
	public static final RegistryObject<Item> PATHOGEN = REGISTRY.register("pathogen", () -> new PathogenItem());
	public static final RegistryObject<Item> ANTIDOTE = REGISTRY.register("antidote", () -> new AntidoteItem());
	public static final RegistryObject<Item> SYRINGE = REGISTRY.register("syringe", () -> new SyringeItem());
	public static final RegistryObject<Item> POISONOUS_PROBOSCIS = REGISTRY.register("poisonous_proboscis", () -> new PoisonousProboscisItem());
	public static final RegistryObject<Item> TERRIFYING_PROBOSCIS = REGISTRY.register("terrifying_proboscis", () -> new TerrifyingProboscisItem());
	public static final RegistryObject<Item> BLINDING_PROBOSCIS = REGISTRY.register("blinding_proboscis", () -> new BlindingProboscisItem());
	public static final RegistryObject<Item> INFECTIOUS_PROBOSCIS = REGISTRY.register("infectious_proboscis", () -> new InfectiousProboscisItem());
	public static final RegistryObject<Item> WITHERED_PROBOSCIS = REGISTRY.register("withered_proboscis", () -> new WitheredProboscisItem());
	public static final RegistryObject<Item> COCOON = block(FightsfrightsModBlocks.COCOON);
	public static final RegistryObject<Item> HIVESTONE = block(FightsfrightsModBlocks.HIVESTONE);
	public static final RegistryObject<Item> PEEPING_HIVESTONE = block(FightsfrightsModBlocks.PEEPING_HIVESTONE);
	public static final RegistryObject<Item> HIVESTONE_SLAB = block(FightsfrightsModBlocks.HIVESTONE_SLAB);
	public static final RegistryObject<Item> HIVESTONE_STAIR = block(FightsfrightsModBlocks.HIVESTONE_STAIR);
	public static final RegistryObject<Item> HIVESTONE_WALL = block(FightsfrightsModBlocks.HIVESTONE_WALL);
	public static final RegistryObject<Item> POLISHED_HIVESTONE_SLAB = block(FightsfrightsModBlocks.POLISHED_HIVESTONE_SLAB);
	public static final RegistryObject<Item> POLISHED_HIVESTONE = block(FightsfrightsModBlocks.POLISHED_HIVESTONE);
	public static final RegistryObject<Item> POLISHED_HIVESTONE_STAIRS = block(FightsfrightsModBlocks.POLISHED_HIVESTONE_STAIRS);
	public static final RegistryObject<Item> POLISHED_HIVESTONE_WALL = block(FightsfrightsModBlocks.POLISHED_HIVESTONE_WALL);
	public static final RegistryObject<Item> HIVESTONE_BRICKS = block(FightsfrightsModBlocks.HIVESTONE_BRICKS);
	public static final RegistryObject<Item> HIVESTONE_BRICKS_SLAB = block(FightsfrightsModBlocks.HIVESTONE_BRICKS_SLAB);
	public static final RegistryObject<Item> HIVESTONE_BRICKS_STAIRS = block(FightsfrightsModBlocks.HIVESTONE_BRICKS_STAIRS);
	public static final RegistryObject<Item> HIVESTONE_BRICKS_WALL = block(FightsfrightsModBlocks.HIVESTONE_BRICKS_WALL);
	public static final RegistryObject<Item> CHISELED_HIVESTONE = block(FightsfrightsModBlocks.CHISELED_HIVESTONE);
	public static final RegistryObject<Item> DREAMCATCHER = block(FightsfrightsModBlocks.DREAMCATCHER);
	public static final RegistryObject<Item> CHITIN = REGISTRY.register("chitin", () -> new ChitinItem());
	public static final RegistryObject<Item> CHITINBLOCK = block(FightsfrightsModBlocks.CHITINBLOCK);
	public static final RegistryObject<Item> SMOOTHCHITIN = block(FightsfrightsModBlocks.SMOOTHCHITIN);
	public static final RegistryObject<Item> CHITINBRICKS = block(FightsfrightsModBlocks.CHITINBRICKS);
	public static final RegistryObject<Item> SMOOTHCHITINSLABS = block(FightsfrightsModBlocks.SMOOTHCHITINSLABS);
	public static final RegistryObject<Item> SMOOTH_CHITIN_STAIRS = block(FightsfrightsModBlocks.SMOOTH_CHITIN_STAIRS);
	public static final RegistryObject<Item> SMOOTH_CHITIN_WALL = block(FightsfrightsModBlocks.SMOOTH_CHITIN_WALL);
	public static final RegistryObject<Item> CHITINBRICKSSLAB = block(FightsfrightsModBlocks.CHITINBRICKSSLAB);
	public static final RegistryObject<Item> CHITINBRICKSSTAIRS = block(FightsfrightsModBlocks.CHITINBRICKSSTAIRS);
	public static final RegistryObject<Item> CHITINBRICKSWALL = block(FightsfrightsModBlocks.CHITINBRICKSWALL);
	public static final RegistryObject<Item> CHISELED_CHITIN = block(FightsfrightsModBlocks.CHISELED_CHITIN);
	public static final RegistryObject<Item> OMINOUS_PLATE = REGISTRY.register("ominous_plate", () -> new OminousPlateItem());
	public static final RegistryObject<Item> NIGHTMARE = REGISTRY.register("nightmare", () -> new NightmareItem());
	public static final RegistryObject<Item> OMINOUS_ESSENCE = REGISTRY.register("ominous_essence", () -> new OminousEssenceItem());
	public static final RegistryObject<Item> OMINOUS_ARMOR_HELMET = REGISTRY.register("ominous_armor_helmet", () -> new OminousArmorItem.Helmet());
	public static final RegistryObject<Item> OMINOUS_ARMOR_CHESTPLATE = REGISTRY.register("ominous_armor_chestplate", () -> new OminousArmorItem.Chestplate());
	public static final RegistryObject<Item> OMINOUS_ARMOR_LEGGINGS = REGISTRY.register("ominous_armor_leggings", () -> new OminousArmorItem.Leggings());
	public static final RegistryObject<Item> OMINOUS_ARMOR_BOOTS = REGISTRY.register("ominous_armor_boots", () -> new OminousArmorItem.Boots());
	public static final RegistryObject<Item> MYSTERYBLOCK = block(FightsfrightsModBlocks.MYSTERYBLOCK);
	public static final RegistryObject<Item> OMINOUS_PLATE_BLOCK = block(FightsfrightsModBlocks.OMINOUS_PLATE_BLOCK);
	public static final RegistryObject<Item> JELLY_BLOCK = block(FightsfrightsModBlocks.JELLY_BLOCK);
	public static final RegistryObject<Item> SMOOTH_JELLY = block(FightsfrightsModBlocks.SMOOTH_JELLY);
	public static final RegistryObject<Item> SMOOTH_JELLY_SLAB = block(FightsfrightsModBlocks.SMOOTH_JELLY_SLAB);
	public static final RegistryObject<Item> SMOOTH_JELLY_STAIRS = block(FightsfrightsModBlocks.SMOOTH_JELLY_STAIRS);
	public static final RegistryObject<Item> SMOOTH_JELLY_WALL = block(FightsfrightsModBlocks.SMOOTH_JELLY_WALL);
	public static final RegistryObject<Item> JELLY_BRICKS = block(FightsfrightsModBlocks.JELLY_BRICKS);
	public static final RegistryObject<Item> JELLY_BRICKS_SLAB = block(FightsfrightsModBlocks.JELLY_BRICKS_SLAB);
	public static final RegistryObject<Item> JELLY_BRICKS_STAIRS = block(FightsfrightsModBlocks.JELLY_BRICKS_STAIRS);
	public static final RegistryObject<Item> JELLY_BRICKS_WALL = block(FightsfrightsModBlocks.JELLY_BRICKS_WALL);
	public static final RegistryObject<Item> CHISELED_JELLY = block(FightsfrightsModBlocks.CHISELED_JELLY);
	public static final RegistryObject<Item> MONSTROUS_PLATE_BLOCK = block(FightsfrightsModBlocks.MONSTROUS_PLATE_BLOCK);
	public static final RegistryObject<Item> TRASHCAN = block(FightsfrightsModBlocks.TRASHCAN);
	public static final RegistryObject<Item> SLOP = block(FightsfrightsModBlocks.SLOP);
	public static final RegistryObject<Item> NETHER_BANSHAA_SPAWN_EGG = REGISTRY.register("nether_banshaa_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.NETHER_BANSHAA, -2630683, -6772262, new Item.Properties()));
	public static final RegistryObject<Item> CIRCUIT_LEVER = block(FightsfrightsModBlocks.CIRCUIT_LEVER);
	public static final RegistryObject<Item> REDSTONE_DISPLAY = block(FightsfrightsModBlocks.REDSTONE_DISPLAY);
	public static final RegistryObject<Item> NETHERSILVERFISH_SPAWN_EGG = REGISTRY.register("nethersilverfish_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.NETHERSILVERFISH, -6727090, -8431794, new Item.Properties()));
	public static final RegistryObject<Item> NETHER_SPIDER_SPAWN_EGG = REGISTRY.register("nether_spider_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.NETHER_SPIDER, -12634848, -6205403, new Item.Properties()));
	public static final RegistryObject<Item> NETHERCAVESPIDER_SPAWN_EGG = REGISTRY.register("nethercavespider_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.NETHERCAVESPIDER, -10275287, -1755557, new Item.Properties()));
	public static final RegistryObject<Item> MIMIC_BEETLES_SPAWN_EGG = REGISTRY.register("mimic_beetles_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.MIMIC_BEETLES, -6710887, -3355444, new Item.Properties()));
	public static final RegistryObject<Item> FIRE_SWARM_SPAWN_EGG = REGISTRY.register("fire_swarm_spawn_egg", () -> new ForgeSpawnEggItem(FightsfrightsModEntities.FIRE_SWARM, -1609964, -808960, new Item.Properties()));

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
