
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.fightsfrights.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.event.BuildCreativeModeTabContentsEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

import net.mcreator.fightsfrights.FightsfrightsMod;

@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD)
public class FightsfrightsModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, FightsfrightsMod.MODID);
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> CREATIVE_TAB = REGISTRY.register("creative_tab",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.fightsfrights.creative_tab")).icon(() -> new ItemStack(FightsfrightsModItems.HEX.get())).displayItems((parameters, tabData) -> {
				tabData.accept(FightsfrightsModItems.ALLMAN_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.SCOWL_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.SHACKLE.get());
				tabData.accept(FightsfrightsModItems.ROTTEN_HANDLE.get());
				tabData.accept(FightsfrightsModItems.GOLDEN_TONGUE.get());
				tabData.accept(FightsfrightsModItems.GOOP.get());
				tabData.accept(FightsfrightsModItems.MONSTER_POP.get());
				tabData.accept(FightsfrightsModItems.SEER_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.PATUTI_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.GILLS.get());
				tabData.accept(FightsfrightsModItems.PIONEER_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.CHIP.get());
				tabData.accept(FightsfrightsModItems.TERRANTULA_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.TERRANTULA_LEG.get());
				tabData.accept(FightsfrightsModItems.BANSHAA_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.BANSHAAS_LUNGS.get());
				tabData.accept(FightsfrightsModItems.MONSTER_SALAD.get());
				tabData.accept(FightsfrightsModBlocks.ROTTEN_BLOCK.get().asItem());
				tabData.accept(FightsfrightsModBlocks.TOTEM_BLOCK.get().asItem());
				tabData.accept(FightsfrightsModBlocks.EMPTY_HEX_BLOCK.get().asItem());
				tabData.accept(FightsfrightsModItems.HEX.get());
				tabData.accept(FightsfrightsModItems.EMPTY_HEX.get());
				tabData.accept(FightsfrightsModBlocks.HEXBLOCK.get().asItem());
				tabData.accept(FightsfrightsModItems.RAVAGER_HORN.get());
				tabData.accept(FightsfrightsModItems.ELDER_SPINE.get());
				tabData.accept(FightsfrightsModItems.MONSTRUOUS_PLATE.get());
				tabData.accept(FightsfrightsModItems.MONSTROUS_ARMOR_HELMET.get());
				tabData.accept(FightsfrightsModItems.MONSTROUS_ARMOR_CHESTPLATE.get());
				tabData.accept(FightsfrightsModItems.MONSTROUS_ARMOR_LEGGINGS.get());
				tabData.accept(FightsfrightsModItems.MONSTROUS_ARMOR_BOOTS.get());
				tabData.accept(FightsfrightsModBlocks.BLIGHT_STEM.get().asItem());
				tabData.accept(FightsfrightsModBlocks.BLLIGHT_CAP_BLOCK.get().asItem());
				tabData.accept(FightsfrightsModBlocks.BLIGHTCAP.get().asItem());
				tabData.accept(FightsfrightsModBlocks.DARK_TRAMA.get().asItem());
				tabData.accept(FightsfrightsModBlocks.BLIGHT_PLANKS.get().asItem());
				tabData.accept(FightsfrightsModBlocks.BLIGHT_HYPHAE.get().asItem());
				tabData.accept(FightsfrightsModBlocks.BLIGHT_STAIRS.get().asItem());
				tabData.accept(FightsfrightsModBlocks.BLIGHT_SLAB.get().asItem());
				tabData.accept(FightsfrightsModBlocks.BLIGHT_FENCE.get().asItem());
				tabData.accept(FightsfrightsModBlocks.BLIGHT_FENCEGATE.get().asItem());
				tabData.accept(FightsfrightsModBlocks.BLIGHT_BUTTON.get().asItem());
				tabData.accept(FightsfrightsModBlocks.BLIGHT_TRAPDOOR.get().asItem());
				tabData.accept(FightsfrightsModBlocks.BLIGHTDOOR.get().asItem());
				tabData.accept(FightsfrightsModBlocks.CRUSHER.get().asItem());
				tabData.accept(FightsfrightsModItems.REANIMATED_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.CHARGED_SCRAP.get());
				tabData.accept(FightsfrightsModItems.CHARGED_FLESH.get());
				tabData.accept(FightsfrightsModItems.GHASTLY_GENERAL_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.POISON_ORB_ITEM.get());
				tabData.accept(FightsfrightsModItems.DEADSTEEL_SCIMITAR.get());
				tabData.accept(FightsfrightsModItems.PUTRID_SCYTHE_2.get());
				tabData.accept(FightsfrightsModItems.SHACKLED_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.PIGLIN_PROSECUTOR_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.BLUNT_JAVELIN.get());
				tabData.accept(FightsfrightsModItems.PUNGENT_SOUP.get());
				tabData.accept(FightsfrightsModItems.OMINOUS_TUSK.get());
				tabData.accept(FightsfrightsModItems.IMPERIAL_ILLAGER_P_1_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.OMINOUS_SCEPTER.get());
				tabData.accept(FightsfrightsModItems.EFFIGY_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModBlocks.VSD.get().asItem());
				tabData.accept(FightsfrightsModItems.CHARGED_CHILI.get());
				tabData.accept(FightsfrightsModItems.CHEESE_STICK.get());
				tabData.accept(FightsfrightsModItems.WICKE_WARMONGER_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.MALICIOUS_MONARCH_P_1_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.CALLOUS_COMMANDER_1_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.ULTIMATE_METHOD_UPDATED.get());
				tabData.accept(FightsfrightsModItems.MIMIC_BEETLE.get());
				tabData.accept(FightsfrightsModItems.GRIMMSQUITO_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.FOREWINGS.get());
				tabData.accept(FightsfrightsModItems.BUG_DUST.get());
				tabData.accept(FightsfrightsModItems.SHADOW_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.MIMENTIS_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.MIMENTIS_CLAW.get());
				tabData.accept(FightsfrightsModItems.MIMENTIS_CLAW_SINGLE_USE.get());
				tabData.accept(FightsfrightsModBlocks.MIME_BLOCK.get().asItem());
				tabData.accept(FightsfrightsModItems.SUPAI_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.PATHOGEN.get());
				tabData.accept(FightsfrightsModItems.ANTIDOTE.get());
				tabData.accept(FightsfrightsModItems.SYRINGE.get());
				tabData.accept(FightsfrightsModItems.POISONOUS_PROBOSCIS.get());
				tabData.accept(FightsfrightsModItems.TERRIFYING_PROBOSCIS.get());
				tabData.accept(FightsfrightsModItems.BLINDING_PROBOSCIS.get());
				tabData.accept(FightsfrightsModItems.INFECTIOUS_PROBOSCIS.get());
				tabData.accept(FightsfrightsModItems.WITHERED_PROBOSCIS.get());
				tabData.accept(FightsfrightsModBlocks.COCOON.get().asItem());
				tabData.accept(FightsfrightsModBlocks.HIVESTONE.get().asItem());
				tabData.accept(FightsfrightsModBlocks.PEEPING_HIVESTONE.get().asItem());
				tabData.accept(FightsfrightsModBlocks.HIVESTONE_SLAB.get().asItem());
				tabData.accept(FightsfrightsModBlocks.HIVESTONE_STAIR.get().asItem());
				tabData.accept(FightsfrightsModBlocks.HIVESTONE_WALL.get().asItem());
				tabData.accept(FightsfrightsModBlocks.POLISHED_HIVESTONE_SLAB.get().asItem());
				tabData.accept(FightsfrightsModBlocks.POLISHED_HIVESTONE.get().asItem());
				tabData.accept(FightsfrightsModBlocks.POLISHED_HIVESTONE_STAIRS.get().asItem());
				tabData.accept(FightsfrightsModBlocks.POLISHED_HIVESTONE_WALL.get().asItem());
				tabData.accept(FightsfrightsModBlocks.HIVESTONE_BRICKS.get().asItem());
				tabData.accept(FightsfrightsModBlocks.HIVESTONE_BRICKS_SLAB.get().asItem());
				tabData.accept(FightsfrightsModBlocks.HIVESTONE_BRICKS_STAIRS.get().asItem());
				tabData.accept(FightsfrightsModBlocks.HIVESTONE_BRICKS_WALL.get().asItem());
				tabData.accept(FightsfrightsModBlocks.CHISELED_HIVESTONE.get().asItem());
				tabData.accept(FightsfrightsModBlocks.DREAMCATCHER.get().asItem());
				tabData.accept(FightsfrightsModItems.CHITIN.get());
				tabData.accept(FightsfrightsModBlocks.CHITINBLOCK.get().asItem());
				tabData.accept(FightsfrightsModBlocks.SMOOTHCHITIN.get().asItem());
				tabData.accept(FightsfrightsModBlocks.CHITINBRICKS.get().asItem());
				tabData.accept(FightsfrightsModBlocks.SMOOTHCHITINSLABS.get().asItem());
				tabData.accept(FightsfrightsModBlocks.SMOOTH_CHITIN_STAIRS.get().asItem());
				tabData.accept(FightsfrightsModBlocks.SMOOTH_CHITIN_WALL.get().asItem());
				tabData.accept(FightsfrightsModBlocks.CHITINBRICKSSLAB.get().asItem());
				tabData.accept(FightsfrightsModBlocks.CHITINBRICKSSTAIRS.get().asItem());
				tabData.accept(FightsfrightsModBlocks.CHITINBRICKSWALL.get().asItem());
				tabData.accept(FightsfrightsModBlocks.CHISELED_CHITIN.get().asItem());
				tabData.accept(FightsfrightsModItems.OMINOUS_PLATE.get());
				tabData.accept(FightsfrightsModItems.NIGHTMARE.get());
				tabData.accept(FightsfrightsModItems.OMINOUS_ESSENCE.get());
				tabData.accept(FightsfrightsModItems.OMINOUS_ARMOR_HELMET.get());
				tabData.accept(FightsfrightsModItems.OMINOUS_ARMOR_CHESTPLATE.get());
				tabData.accept(FightsfrightsModItems.OMINOUS_ARMOR_LEGGINGS.get());
				tabData.accept(FightsfrightsModItems.OMINOUS_ARMOR_BOOTS.get());
				tabData.accept(FightsfrightsModBlocks.MYSTERYBLOCK.get().asItem());
				tabData.accept(FightsfrightsModBlocks.OMINOUS_PLATE_BLOCK.get().asItem());
				tabData.accept(FightsfrightsModBlocks.JELLY_BLOCK.get().asItem());
				tabData.accept(FightsfrightsModBlocks.SMOOTH_JELLY.get().asItem());
				tabData.accept(FightsfrightsModBlocks.SMOOTH_JELLY_SLAB.get().asItem());
				tabData.accept(FightsfrightsModBlocks.SMOOTH_JELLY_STAIRS.get().asItem());
				tabData.accept(FightsfrightsModBlocks.SMOOTH_JELLY_WALL.get().asItem());
				tabData.accept(FightsfrightsModBlocks.JELLY_BRICKS.get().asItem());
				tabData.accept(FightsfrightsModBlocks.JELLY_BRICKS_SLAB.get().asItem());
				tabData.accept(FightsfrightsModBlocks.JELLY_BRICKS_STAIRS.get().asItem());
				tabData.accept(FightsfrightsModBlocks.JELLY_BRICKS_WALL.get().asItem());
				tabData.accept(FightsfrightsModBlocks.CHISELED_JELLY.get().asItem());
				tabData.accept(FightsfrightsModBlocks.TRASHCAN.get().asItem());
				tabData.accept(FightsfrightsModBlocks.SLOP.get().asItem());
				tabData.accept(FightsfrightsModBlocks.CIRCUIT_LEVER.get().asItem());
				tabData.accept(FightsfrightsModBlocks.REDSTONE_DISPLAY.get().asItem());
				tabData.accept(FightsfrightsModItems.MIMIC_BEETLES_SPAWN_EGG.get());
				tabData.accept(FightsfrightsModItems.FIRE_SWARM_SPAWN_EGG.get());
			}).build());

	@SubscribeEvent
	public static void buildTabContentsVanilla(BuildCreativeModeTabContentsEvent tabData) {
		if (tabData.getTabKey() == CreativeModeTabs.SPAWN_EGGS) {
			tabData.accept(FightsfrightsModItems.ALLMAN_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.SCOWL_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.SEER_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.PATUTI_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.PIONEER_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.TERRANTULA_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.BANSHAA_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.REANIMATED_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.GHASTLY_GENERAL_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.SHACKLED_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.PIGLIN_PROSECUTOR_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.IMPERIAL_ILLAGER_P_1_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.EFFIGY_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.GRIMMSQUITO_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.SHADOW_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.MIMENTIS_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.NETHERSILVERFISH_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.NETHER_SPIDER_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.NETHERCAVESPIDER_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.MIMIC_BEETLES_SPAWN_EGG.get());
			tabData.accept(FightsfrightsModItems.FIRE_SWARM_SPAWN_EGG.get());
		} else if (tabData.getTabKey() == CreativeModeTabs.INGREDIENTS) {
			tabData.accept(FightsfrightsModItems.SHACKLE.get());
			tabData.accept(FightsfrightsModItems.ROTTEN_HANDLE.get());
			tabData.accept(FightsfrightsModItems.GOOP.get());
			tabData.accept(FightsfrightsModItems.ELDER_SPINE.get());
			tabData.accept(FightsfrightsModItems.MONSTRUOUS_PLATE.get());
			tabData.accept(FightsfrightsModItems.CHARGED_SCRAP.get());
			tabData.accept(FightsfrightsModItems.MIMIC_BEETLE.get());
			tabData.accept(FightsfrightsModItems.CHITIN.get());
			tabData.accept(FightsfrightsModItems.OMINOUS_PLATE.get());
			tabData.accept(FightsfrightsModItems.NIGHTMARE.get());
			tabData.accept(FightsfrightsModBlocks.OMINOUS_PLATE_BLOCK.get().asItem());
			tabData.accept(FightsfrightsModBlocks.MONSTROUS_PLATE_BLOCK.get().asItem());
		} else if (tabData.getTabKey() == CreativeModeTabs.FOOD_AND_DRINKS) {
			tabData.accept(FightsfrightsModItems.ROTTEN_HANDLE.get());
			tabData.accept(FightsfrightsModItems.GOLDEN_TONGUE.get());
			tabData.accept(FightsfrightsModItems.GOOP.get());
			tabData.accept(FightsfrightsModItems.MONSTER_POP.get());
			tabData.accept(FightsfrightsModItems.GILLS.get());
			tabData.accept(FightsfrightsModItems.CHIP.get());
			tabData.accept(FightsfrightsModItems.TERRANTULA_LEG.get());
			tabData.accept(FightsfrightsModItems.BANSHAAS_LUNGS.get());
			tabData.accept(FightsfrightsModItems.MONSTER_SALAD.get());
			tabData.accept(FightsfrightsModItems.CHARGED_FLESH.get());
			tabData.accept(FightsfrightsModItems.PUNGENT_SOUP.get());
			tabData.accept(FightsfrightsModItems.CHARGED_CHILI.get());
			tabData.accept(FightsfrightsModItems.CHEESE_STICK.get());
			tabData.accept(FightsfrightsModItems.FOREWINGS.get());
			tabData.accept(FightsfrightsModItems.BUG_DUST.get());
			tabData.accept(FightsfrightsModItems.PATHOGEN.get());
			tabData.accept(FightsfrightsModItems.OMINOUS_ESSENCE.get());
		} else if (tabData.getTabKey() == CreativeModeTabs.NATURAL_BLOCKS) {
			tabData.accept(FightsfrightsModBlocks.ROTTEN_BLOCK.get().asItem());
			tabData.accept(FightsfrightsModBlocks.BLIGHT_STEM.get().asItem());
			tabData.accept(FightsfrightsModBlocks.BLLIGHT_CAP_BLOCK.get().asItem());
			tabData.accept(FightsfrightsModBlocks.BLIGHTCAP.get().asItem());
			tabData.accept(FightsfrightsModBlocks.BLIGHT_HYPHAE.get().asItem());
			tabData.accept(FightsfrightsModBlocks.FISSURED_NETHERRACK.get().asItem());
			tabData.accept(FightsfrightsModBlocks.COCOON.get().asItem());
			tabData.accept(FightsfrightsModBlocks.HIVESTONE.get().asItem());
			tabData.accept(FightsfrightsModBlocks.PEEPING_HIVESTONE.get().asItem());
			tabData.accept(FightsfrightsModBlocks.JELLY_BLOCK.get().asItem());
			tabData.accept(FightsfrightsModBlocks.SLOP.get().asItem());
		} else if (tabData.getTabKey() == CreativeModeTabs.FUNCTIONAL_BLOCKS) {
			tabData.accept(FightsfrightsModBlocks.TOTEM_BLOCK.get().asItem());
			tabData.accept(FightsfrightsModBlocks.EMPTY_HEX_BLOCK.get().asItem());
			tabData.accept(FightsfrightsModBlocks.HEXBLOCK.get().asItem());
			tabData.accept(FightsfrightsModBlocks.CRUSHER.get().asItem());
			tabData.accept(FightsfrightsModBlocks.VSD.get().asItem());
			tabData.accept(FightsfrightsModBlocks.PEEPING_HIVESTONE.get().asItem());
			tabData.accept(FightsfrightsModBlocks.MYSTERYBLOCK.get().asItem());
			tabData.accept(FightsfrightsModBlocks.TRASHCAN.get().asItem());
		} else if (tabData.getTabKey() == CreativeModeTabs.TOOLS_AND_UTILITIES) {
			tabData.accept(FightsfrightsModItems.HEX.get());
			tabData.accept(FightsfrightsModItems.EMPTY_HEX.get());
			tabData.accept(FightsfrightsModItems.RAVAGER_HORN.get());
			tabData.accept(FightsfrightsModItems.CHARGED_SCRAP.get());
			tabData.accept(FightsfrightsModItems.POISON_ORB_ITEM.get());
			tabData.accept(FightsfrightsModItems.PUTRID_SCYTHE_2.get());
			tabData.accept(FightsfrightsModItems.ALLBOMB.get());
			tabData.accept(FightsfrightsModItems.OMINOUS_SCEPTER.get());
			tabData.accept(FightsfrightsModItems.MIMENTIS_CLAW.get());
			tabData.accept(FightsfrightsModItems.MIMENTIS_CLAW_SINGLE_USE.get());
			tabData.accept(FightsfrightsModItems.ANTIDOTE.get());
			tabData.accept(FightsfrightsModItems.SYRINGE.get());
			tabData.accept(FightsfrightsModBlocks.DREAMCATCHER.get().asItem());
		} else if (tabData.getTabKey() == CreativeModeTabs.COMBAT) {
			tabData.accept(FightsfrightsModItems.MONSTROUS_ARMOR_HELMET.get());
			tabData.accept(FightsfrightsModItems.MONSTROUS_ARMOR_CHESTPLATE.get());
			tabData.accept(FightsfrightsModItems.MONSTROUS_ARMOR_LEGGINGS.get());
			tabData.accept(FightsfrightsModItems.MONSTROUS_ARMOR_BOOTS.get());
			tabData.accept(FightsfrightsModItems.DEADSTEEL_SCIMITAR.get());
			tabData.accept(FightsfrightsModItems.BLUNT_JAVELIN.get());
			tabData.accept(FightsfrightsModItems.OMINOUS_TUSK.get());
			tabData.accept(FightsfrightsModItems.OMINOUS_SCEPTER.get());
			tabData.accept(FightsfrightsModItems.ULTIMATE_METHOD_UPDATED.get());
			tabData.accept(FightsfrightsModItems.POISONOUS_PROBOSCIS.get());
			tabData.accept(FightsfrightsModItems.TERRIFYING_PROBOSCIS.get());
			tabData.accept(FightsfrightsModItems.BLINDING_PROBOSCIS.get());
			tabData.accept(FightsfrightsModItems.INFECTIOUS_PROBOSCIS.get());
			tabData.accept(FightsfrightsModItems.WITHERED_PROBOSCIS.get());
			tabData.accept(FightsfrightsModItems.OMINOUS_ARMOR_HELMET.get());
			tabData.accept(FightsfrightsModItems.OMINOUS_ARMOR_CHESTPLATE.get());
			tabData.accept(FightsfrightsModItems.OMINOUS_ARMOR_LEGGINGS.get());
			tabData.accept(FightsfrightsModItems.OMINOUS_ARMOR_BOOTS.get());
		} else if (tabData.getTabKey() == CreativeModeTabs.BUILDING_BLOCKS) {
			tabData.accept(FightsfrightsModBlocks.BLIGHT_STEM.get().asItem());
			tabData.accept(FightsfrightsModBlocks.DARK_TRAMA.get().asItem());
			tabData.accept(FightsfrightsModBlocks.BLIGHT_PLANKS.get().asItem());
			tabData.accept(FightsfrightsModBlocks.BLIGHT_HYPHAE.get().asItem());
			tabData.accept(FightsfrightsModBlocks.BLIGHT_STAIRS.get().asItem());
			tabData.accept(FightsfrightsModBlocks.BLIGHT_SLAB.get().asItem());
			tabData.accept(FightsfrightsModBlocks.BLIGHT_FENCE.get().asItem());
			tabData.accept(FightsfrightsModBlocks.BLIGHT_FENCEGATE.get().asItem());
			tabData.accept(FightsfrightsModBlocks.BLIGHT_BUTTON.get().asItem());
			tabData.accept(FightsfrightsModBlocks.BLIGHT_TRAPDOOR.get().asItem());
			tabData.accept(FightsfrightsModBlocks.BLIGHTDOOR.get().asItem());
			tabData.accept(FightsfrightsModBlocks.MIME_BLOCK.get().asItem());
			tabData.accept(FightsfrightsModBlocks.HIVESTONE.get().asItem());
			tabData.accept(FightsfrightsModBlocks.HIVESTONE_SLAB.get().asItem());
			tabData.accept(FightsfrightsModBlocks.HIVESTONE_STAIR.get().asItem());
			tabData.accept(FightsfrightsModBlocks.HIVESTONE_WALL.get().asItem());
			tabData.accept(FightsfrightsModBlocks.POLISHED_HIVESTONE_SLAB.get().asItem());
			tabData.accept(FightsfrightsModBlocks.POLISHED_HIVESTONE.get().asItem());
			tabData.accept(FightsfrightsModBlocks.POLISHED_HIVESTONE_STAIRS.get().asItem());
			tabData.accept(FightsfrightsModBlocks.POLISHED_HIVESTONE_WALL.get().asItem());
			tabData.accept(FightsfrightsModBlocks.HIVESTONE_BRICKS.get().asItem());
			tabData.accept(FightsfrightsModBlocks.HIVESTONE_BRICKS_SLAB.get().asItem());
			tabData.accept(FightsfrightsModBlocks.HIVESTONE_BRICKS_STAIRS.get().asItem());
			tabData.accept(FightsfrightsModBlocks.HIVESTONE_BRICKS_WALL.get().asItem());
			tabData.accept(FightsfrightsModBlocks.CHISELED_HIVESTONE.get().asItem());
			tabData.accept(FightsfrightsModBlocks.CHITINBLOCK.get().asItem());
			tabData.accept(FightsfrightsModBlocks.SMOOTHCHITIN.get().asItem());
			tabData.accept(FightsfrightsModBlocks.CHITINBRICKS.get().asItem());
			tabData.accept(FightsfrightsModBlocks.SMOOTHCHITINSLABS.get().asItem());
			tabData.accept(FightsfrightsModBlocks.SMOOTH_CHITIN_STAIRS.get().asItem());
			tabData.accept(FightsfrightsModBlocks.SMOOTH_CHITIN_WALL.get().asItem());
			tabData.accept(FightsfrightsModBlocks.CHITINBRICKSSLAB.get().asItem());
			tabData.accept(FightsfrightsModBlocks.CHITINBRICKSSTAIRS.get().asItem());
			tabData.accept(FightsfrightsModBlocks.CHITINBRICKSWALL.get().asItem());
			tabData.accept(FightsfrightsModBlocks.CHISELED_CHITIN.get().asItem());
			tabData.accept(FightsfrightsModBlocks.SMOOTH_JELLY.get().asItem());
			tabData.accept(FightsfrightsModBlocks.SMOOTH_JELLY_SLAB.get().asItem());
			tabData.accept(FightsfrightsModBlocks.SMOOTH_JELLY_STAIRS.get().asItem());
			tabData.accept(FightsfrightsModBlocks.SMOOTH_JELLY_WALL.get().asItem());
			tabData.accept(FightsfrightsModBlocks.JELLY_BRICKS.get().asItem());
			tabData.accept(FightsfrightsModBlocks.JELLY_BRICKS_SLAB.get().asItem());
			tabData.accept(FightsfrightsModBlocks.JELLY_BRICKS_STAIRS.get().asItem());
			tabData.accept(FightsfrightsModBlocks.JELLY_BRICKS_WALL.get().asItem());
			tabData.accept(FightsfrightsModBlocks.CHISELED_JELLY.get().asItem());
		} else if (tabData.getTabKey() == CreativeModeTabs.REDSTONE_BLOCKS) {
			tabData.accept(FightsfrightsModBlocks.TRASHCAN.get().asItem());
			tabData.accept(FightsfrightsModBlocks.CIRCUIT_LEVER.get().asItem());
			tabData.accept(FightsfrightsModBlocks.REDSTONE_DISPLAY.get().asItem());
		}
	}
}
