
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.fightsfrights.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.Block;

import net.mcreator.fightsfrights.block.VSDBlock;
import net.mcreator.fightsfrights.block.TrashcanBlock;
import net.mcreator.fightsfrights.block.TotemBlockBlock;
import net.mcreator.fightsfrights.block.SmoothchitinslabsBlock;
import net.mcreator.fightsfrights.block.SmoothchitinBlock;
import net.mcreator.fightsfrights.block.SmoothJellyWallBlock;
import net.mcreator.fightsfrights.block.SmoothJellyStairsBlock;
import net.mcreator.fightsfrights.block.SmoothJellySlabBlock;
import net.mcreator.fightsfrights.block.SmoothJellyBlock;
import net.mcreator.fightsfrights.block.SmoothChitinWallBlock;
import net.mcreator.fightsfrights.block.SmoothChitinStairsBlock;
import net.mcreator.fightsfrights.block.SlopBlock;
import net.mcreator.fightsfrights.block.RottenBlockBlock;
import net.mcreator.fightsfrights.block.RedstoneDisplayBlock;
import net.mcreator.fightsfrights.block.PolishedHivestoneWallBlock;
import net.mcreator.fightsfrights.block.PolishedHivestoneStairsBlock;
import net.mcreator.fightsfrights.block.PolishedHivestoneSlabBlock;
import net.mcreator.fightsfrights.block.PolishedHivestoneBlock;
import net.mcreator.fightsfrights.block.PeepingHivestoneBlock;
import net.mcreator.fightsfrights.block.OminousPlateBlockBlock;
import net.mcreator.fightsfrights.block.MysteryblockBlock;
import net.mcreator.fightsfrights.block.MonstrousPlateBlockBlock;
import net.mcreator.fightsfrights.block.MimeBlockBlock;
import net.mcreator.fightsfrights.block.JellyBricksWallBlock;
import net.mcreator.fightsfrights.block.JellyBricksStairsBlock;
import net.mcreator.fightsfrights.block.JellyBricksSlabBlock;
import net.mcreator.fightsfrights.block.JellyBricksBlock;
import net.mcreator.fightsfrights.block.JellyBlockBlock;
import net.mcreator.fightsfrights.block.HivestoneWallBlock;
import net.mcreator.fightsfrights.block.HivestoneStairBlock;
import net.mcreator.fightsfrights.block.HivestoneSlabBlock;
import net.mcreator.fightsfrights.block.HivestoneBricksWallBlock;
import net.mcreator.fightsfrights.block.HivestoneBricksStairsBlock;
import net.mcreator.fightsfrights.block.HivestoneBricksSlabBlock;
import net.mcreator.fightsfrights.block.HivestoneBricksBlock;
import net.mcreator.fightsfrights.block.HivestoneBlock;
import net.mcreator.fightsfrights.block.HexblockBlock;
import net.mcreator.fightsfrights.block.FissuredNetherrackBlock;
import net.mcreator.fightsfrights.block.EmptyHexBlockBlock;
import net.mcreator.fightsfrights.block.DreamcatcherBlock;
import net.mcreator.fightsfrights.block.DarkTramaBlock;
import net.mcreator.fightsfrights.block.CrusherBlock;
import net.mcreator.fightsfrights.block.CocoonBlock;
import net.mcreator.fightsfrights.block.CircuitLeverBlock;
import net.mcreator.fightsfrights.block.ChitinbrickswallBlock;
import net.mcreator.fightsfrights.block.ChitinbricksstairsBlock;
import net.mcreator.fightsfrights.block.ChitinbricksslabBlock;
import net.mcreator.fightsfrights.block.ChitinbricksBlock;
import net.mcreator.fightsfrights.block.ChitinblockBlock;
import net.mcreator.fightsfrights.block.ChiseledJellyBlock;
import net.mcreator.fightsfrights.block.ChiseledHivestoneBlock;
import net.mcreator.fightsfrights.block.ChiseledChitinBlock;
import net.mcreator.fightsfrights.block.BllightCapBlockBlock;
import net.mcreator.fightsfrights.block.BlightdoorBlock;
import net.mcreator.fightsfrights.block.BlightcapBlock;
import net.mcreator.fightsfrights.block.BlightTrapdoorBlock;
import net.mcreator.fightsfrights.block.BlightStemBlock;
import net.mcreator.fightsfrights.block.BlightStairsBlock;
import net.mcreator.fightsfrights.block.BlightSlabBlock;
import net.mcreator.fightsfrights.block.BlightPlanksBlock;
import net.mcreator.fightsfrights.block.BlightHyphaeBlock;
import net.mcreator.fightsfrights.block.BlightFencegateBlock;
import net.mcreator.fightsfrights.block.BlightFenceBlock;
import net.mcreator.fightsfrights.block.BlightButtonBlock;
import net.mcreator.fightsfrights.FightsfrightsMod;

public class FightsfrightsModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(FightsfrightsMod.MODID);
	public static final DeferredBlock<Block> ROTTEN_BLOCK = REGISTRY.register("rotten_block", RottenBlockBlock::new);
	public static final DeferredBlock<Block> TOTEM_BLOCK = REGISTRY.register("totem_block", TotemBlockBlock::new);
	public static final DeferredBlock<Block> EMPTY_HEX_BLOCK = REGISTRY.register("empty_hex_block", EmptyHexBlockBlock::new);
	public static final DeferredBlock<Block> HEXBLOCK = REGISTRY.register("hexblock", HexblockBlock::new);
	public static final DeferredBlock<Block> BLIGHT_STEM = REGISTRY.register("blight_stem", BlightStemBlock::new);
	public static final DeferredBlock<Block> BLLIGHT_CAP_BLOCK = REGISTRY.register("bllight_cap_block", BllightCapBlockBlock::new);
	public static final DeferredBlock<Block> BLIGHTCAP = REGISTRY.register("blightcap", BlightcapBlock::new);
	public static final DeferredBlock<Block> DARK_TRAMA = REGISTRY.register("dark_trama", DarkTramaBlock::new);
	public static final DeferredBlock<Block> BLIGHT_PLANKS = REGISTRY.register("blight_planks", BlightPlanksBlock::new);
	public static final DeferredBlock<Block> BLIGHT_HYPHAE = REGISTRY.register("blight_hyphae", BlightHyphaeBlock::new);
	public static final DeferredBlock<Block> BLIGHT_STAIRS = REGISTRY.register("blight_stairs", BlightStairsBlock::new);
	public static final DeferredBlock<Block> BLIGHT_SLAB = REGISTRY.register("blight_slab", BlightSlabBlock::new);
	public static final DeferredBlock<Block> BLIGHT_FENCE = REGISTRY.register("blight_fence", BlightFenceBlock::new);
	public static final DeferredBlock<Block> BLIGHT_FENCEGATE = REGISTRY.register("blight_fencegate", BlightFencegateBlock::new);
	public static final DeferredBlock<Block> BLIGHT_BUTTON = REGISTRY.register("blight_button", BlightButtonBlock::new);
	public static final DeferredBlock<Block> BLIGHT_TRAPDOOR = REGISTRY.register("blight_trapdoor", BlightTrapdoorBlock::new);
	public static final DeferredBlock<Block> BLIGHTDOOR = REGISTRY.register("blightdoor", BlightdoorBlock::new);
	public static final DeferredBlock<Block> CRUSHER = REGISTRY.register("crusher", CrusherBlock::new);
	public static final DeferredBlock<Block> VSD = REGISTRY.register("vsd", VSDBlock::new);
	public static final DeferredBlock<Block> FISSURED_NETHERRACK = REGISTRY.register("fissured_netherrack", FissuredNetherrackBlock::new);
	public static final DeferredBlock<Block> MIME_BLOCK = REGISTRY.register("mime_block", MimeBlockBlock::new);
	public static final DeferredBlock<Block> COCOON = REGISTRY.register("cocoon", CocoonBlock::new);
	public static final DeferredBlock<Block> HIVESTONE = REGISTRY.register("hivestone", HivestoneBlock::new);
	public static final DeferredBlock<Block> PEEPING_HIVESTONE = REGISTRY.register("peeping_hivestone", PeepingHivestoneBlock::new);
	public static final DeferredBlock<Block> HIVESTONE_SLAB = REGISTRY.register("hivestone_slab", HivestoneSlabBlock::new);
	public static final DeferredBlock<Block> HIVESTONE_STAIR = REGISTRY.register("hivestone_stair", HivestoneStairBlock::new);
	public static final DeferredBlock<Block> HIVESTONE_WALL = REGISTRY.register("hivestone_wall", HivestoneWallBlock::new);
	public static final DeferredBlock<Block> POLISHED_HIVESTONE_SLAB = REGISTRY.register("polished_hivestone_slab", PolishedHivestoneSlabBlock::new);
	public static final DeferredBlock<Block> POLISHED_HIVESTONE = REGISTRY.register("polished_hivestone", PolishedHivestoneBlock::new);
	public static final DeferredBlock<Block> POLISHED_HIVESTONE_STAIRS = REGISTRY.register("polished_hivestone_stairs", PolishedHivestoneStairsBlock::new);
	public static final DeferredBlock<Block> POLISHED_HIVESTONE_WALL = REGISTRY.register("polished_hivestone_wall", PolishedHivestoneWallBlock::new);
	public static final DeferredBlock<Block> HIVESTONE_BRICKS = REGISTRY.register("hivestone_bricks", HivestoneBricksBlock::new);
	public static final DeferredBlock<Block> HIVESTONE_BRICKS_SLAB = REGISTRY.register("hivestone_bricks_slab", HivestoneBricksSlabBlock::new);
	public static final DeferredBlock<Block> HIVESTONE_BRICKS_STAIRS = REGISTRY.register("hivestone_bricks_stairs", HivestoneBricksStairsBlock::new);
	public static final DeferredBlock<Block> HIVESTONE_BRICKS_WALL = REGISTRY.register("hivestone_bricks_wall", HivestoneBricksWallBlock::new);
	public static final DeferredBlock<Block> CHISELED_HIVESTONE = REGISTRY.register("chiseled_hivestone", ChiseledHivestoneBlock::new);
	public static final DeferredBlock<Block> DREAMCATCHER = REGISTRY.register("dreamcatcher", DreamcatcherBlock::new);
	public static final DeferredBlock<Block> CHITINBLOCK = REGISTRY.register("chitinblock", ChitinblockBlock::new);
	public static final DeferredBlock<Block> SMOOTHCHITIN = REGISTRY.register("smoothchitin", SmoothchitinBlock::new);
	public static final DeferredBlock<Block> CHITINBRICKS = REGISTRY.register("chitinbricks", ChitinbricksBlock::new);
	public static final DeferredBlock<Block> SMOOTHCHITINSLABS = REGISTRY.register("smoothchitinslabs", SmoothchitinslabsBlock::new);
	public static final DeferredBlock<Block> SMOOTH_CHITIN_STAIRS = REGISTRY.register("smooth_chitin_stairs", SmoothChitinStairsBlock::new);
	public static final DeferredBlock<Block> SMOOTH_CHITIN_WALL = REGISTRY.register("smooth_chitin_wall", SmoothChitinWallBlock::new);
	public static final DeferredBlock<Block> CHITINBRICKSSLAB = REGISTRY.register("chitinbricksslab", ChitinbricksslabBlock::new);
	public static final DeferredBlock<Block> CHITINBRICKSSTAIRS = REGISTRY.register("chitinbricksstairs", ChitinbricksstairsBlock::new);
	public static final DeferredBlock<Block> CHITINBRICKSWALL = REGISTRY.register("chitinbrickswall", ChitinbrickswallBlock::new);
	public static final DeferredBlock<Block> CHISELED_CHITIN = REGISTRY.register("chiseled_chitin", ChiseledChitinBlock::new);
	public static final DeferredBlock<Block> MYSTERYBLOCK = REGISTRY.register("mysteryblock", MysteryblockBlock::new);
	public static final DeferredBlock<Block> OMINOUS_PLATE_BLOCK = REGISTRY.register("ominous_plate_block", OminousPlateBlockBlock::new);
	public static final DeferredBlock<Block> JELLY_BLOCK = REGISTRY.register("jelly_block", JellyBlockBlock::new);
	public static final DeferredBlock<Block> SMOOTH_JELLY = REGISTRY.register("smooth_jelly", SmoothJellyBlock::new);
	public static final DeferredBlock<Block> SMOOTH_JELLY_SLAB = REGISTRY.register("smooth_jelly_slab", SmoothJellySlabBlock::new);
	public static final DeferredBlock<Block> SMOOTH_JELLY_STAIRS = REGISTRY.register("smooth_jelly_stairs", SmoothJellyStairsBlock::new);
	public static final DeferredBlock<Block> SMOOTH_JELLY_WALL = REGISTRY.register("smooth_jelly_wall", SmoothJellyWallBlock::new);
	public static final DeferredBlock<Block> JELLY_BRICKS = REGISTRY.register("jelly_bricks", JellyBricksBlock::new);
	public static final DeferredBlock<Block> JELLY_BRICKS_SLAB = REGISTRY.register("jelly_bricks_slab", JellyBricksSlabBlock::new);
	public static final DeferredBlock<Block> JELLY_BRICKS_STAIRS = REGISTRY.register("jelly_bricks_stairs", JellyBricksStairsBlock::new);
	public static final DeferredBlock<Block> JELLY_BRICKS_WALL = REGISTRY.register("jelly_bricks_wall", JellyBricksWallBlock::new);
	public static final DeferredBlock<Block> CHISELED_JELLY = REGISTRY.register("chiseled_jelly", ChiseledJellyBlock::new);
	public static final DeferredBlock<Block> MONSTROUS_PLATE_BLOCK = REGISTRY.register("monstrous_plate_block", MonstrousPlateBlockBlock::new);
	public static final DeferredBlock<Block> TRASHCAN = REGISTRY.register("trashcan", TrashcanBlock::new);
	public static final DeferredBlock<Block> SLOP = REGISTRY.register("slop", SlopBlock::new);
	public static final DeferredBlock<Block> CIRCUIT_LEVER = REGISTRY.register("circuit_lever", CircuitLeverBlock::new);
	public static final DeferredBlock<Block> REDSTONE_DISPLAY = REGISTRY.register("redstone_display", RedstoneDisplayBlock::new);
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
